### ISSUE TITLE
401 Unauthorized error from the repository when compiling with gradle

### ISSUE THREAD

**Issue by jd-alexander** [anjlab/android-inapp-billing-v3#101]
![error](https://cloud.githubusercontent.com/assets/1509205/8116455/ea601f20-1047-11e5-82f8-f002d780455b.PNG)

**Comment by 6istik** [comment]
Could you clarify what is going on? I've got the same today

**Comment by giodss** [comment]
I also got this problem. I assume this is a server side problem.

**Comment by yfsx** [comment]
same goes here.. what happened? hope this will fixed as soon as possible :)

really great and simple lib anyway, i love it!

**Comment by supertoonz** [comment]
What happened?

**Comment by supertoonz** [comment]
Now I created LICENSE file in root project and Sync project again. It work for me.

**Comment by MinceMan** [comment]
I think this was obviously a temporary jcenter error that has nothing to do with this repo. Recommend closing this issues with no action.

**Comment by yfsx** [comment]
yes i think so. thanks!
