### ISSUE TITLE
onProductPurchased not get called for subscription product

### ISSUE THREAD

**Issue by maddy04** [anjlab/android-inapp-billing-v3#103]
onProductPurchased not get called for subscription product while the google alert show successfull payment

**Comment by pkarolis** [comment]
Make sure your Activity which is making the purchase has overridden onActivityResult method.
It has to look like this:

```protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (!bp.handleActivityResult(requestCode, resultCode, data))
            super.onActivityResult(requestCode, resultCode, data);
    }

Once you correctly override onActivityResult  onProductPurchased will be called first time you make a purchase. 


Check sample app for more detailed exampled and how it overrides onActivityResult:
https://github.com/anjlab/android-inapp-billing-v3/blob/master/sample/src/com/anjlab/android/iab/v3/sample2/MainActivity.java

**Comment by serggl** [comment]
seems like the same as #94, can you confirm this @maddy04 ?

**Comment by sayoojvalsan** [comment]
When are you planning to fix the issue?

**Comment by nambv** [comment]
@serggl did you fix this issue? thanks!

**Comment by serggl** [comment]
@nambv I made a fix to an issue #94, but Im not sure if it will also fix this one. @maddy04 did not confirmed my guess yet

**Comment by sayoojvalsan** [comment]
Actually for me its working. I made a mistake of calling api for one-timeProduct instead of subscription.

I called bp.purchase instead of bp.subscribe. After the changes, I am all set. 

Let me know if I am missing anything else.

**Comment by nambv** [comment]
@serggl okie thanks a lot :p
