### ISSUE TITLE
Gradle 'android-inapp-billing-v3-1.0.26' project refresh failed

### ISSUE THREAD

**Issue by umeshlakhani7170** [anjlab/android-inapp-billing-v3#106]
Error:No such property: sonatypeRepo for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

**Comment by EdbertChan** [comment]
Bump for interest. Getting same error.

**Comment by sherdle** [comment]
Removing the following lines from the build.gradle (in the library module) fixed it for me.
```java
repository(url: sonatypeRepo) {
            authentication(userName: sonatypeUsername, password: sonatypePassword)
 }
```

**Comment by serggl** [comment]
these lines needed to publics library. You need either remove these lines or create `gradle.properties` file and define those empty properties there
