### ISSUE TITLE
Nothing showed when call   bp.consumePurchase(id);

### ISSUE THREAD

**Issue by omegaes** [anjlab/android-inapp-billing-v3#107]
Hello
My problem is : no dialog shows when i call   bp.consumePurchase(id); or      bp.purchase(getActivity(),id)
no error , no exciption, nothing :(

**Comment by dharmik** [comment]
Same problem with me :(

**Comment by jhess2991** [comment]
same here, sigh.

**Comment by javiersantos** [comment]
Are you maybe using ProGuard?

If you do, add this lines:
```
-keep class com.android.vending.billing.**
-keepattributes *Annotation*
-keep public class com.android.vending.licensing.ILicensingService
```

**Comment by serggl** [comment]
just to clarify: are you testing on a device?

**Comment by viksoffice** [comment]
I am facing the same problem in android device. Nothing happens in phone when i call bp.consumePurchase("packageId");

**Comment by adaneam** [comment]
Facing the same issue. Nothing happens after calling bp.purchase()

**Comment by gwebalex** [comment]
@serggl , I am facing the same issue. And. Yes. I am testing on a real device too.
// I have an Android 4.1.2 HTC phone.

**Comment by serggl** [comment]
sounds like there are multiple issues mixed here, and both have too few details.
If I would answer to:
> no dialog shows when i call bp.consumePurchase(id)

I would say that this call wont show any UI. It will just return `true` or `false` instead

If I would answer to:
> no dialog shows when i call bp.purchase(getActivity(),id)

I would say that you guys are missing some step from the [README](https://github.com/anjlab/android-inapp-billing-v3/blob/master/README.md) or [testing guide](https://developer.android.com/google/play/billing/billing_testing.html)

**Comment by 1hakr** [comment]
Working solution for in app Purchase problem on Redmi phones:
Go to Installed Apps -> Google Play Store -> Permission manager, enable "Start in background" permission.
