### ISSUE TITLE
onBillingError() event fired when user aborts/cancels payment workflow

### ISSUE THREAD

**Issue by adaneam** [anjlab/android-inapp-billing-v3#109]
Should this event be fired when user cancels payment workflow(by pressing back or tapping outside)?
Since this even is fired even on abort, how do you differentiate between actual error and cancel event?

**Comment by kabouzeid** [comment]
I am interested in that as well

**Comment by serggl** [comment]
`BILLING_RESPONSE_RESULT_USER_CANCELED` error code is defined for this case
