### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by onuryurtturk** [anjlab/android-inapp-billing-v3#110]
Product id and licence is okay. I checked both of them but i got "Authentication required, Sign in with google account" error. How can I handle this?

**Comment by byhtada** [comment]
I have this problem too.

**Comment by serggl** [comment]
I guess you need to have google apps installed and a google account linked
in phone settings?

On Tue, Aug 11, 2015 at 8:15 AM byhtada <notifications@github.com> wrote:

> I have this problem too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anjlab/android-inapp-billing-v3/issues/110#issuecomment-129708596>
> .
>
-- 
Sergey, AnjLab

**Comment by byhtada** [comment]
Apps installed, google account linked.
Test in 2 devices.

public class BuyCoin1 extends Activity  implements BillingProcessor.IBillingHandler  {

    BillingProcessor bp;

    private static final String PRODUCT_ID = "com.bclock.1000coins";
    private static final String LICENSE_KEY = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.coin_buy);

        bp = new BillingProcessor(this, LICENSE_KEY, this);
    }

    public void onClickBuy(View v){
        bp.purchase(this, PRODUCT_ID);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (!bp.handleActivityResult(requestCode, resultCode, data))
            super.onActivityResult(requestCode, resultCode, data);
    }

    @Override
    public void onProductPurchased(String s, TransactionDetails transactionDetails) {

    }

    @Override
    public void onPurchaseHistoryRestored() {

    }

    @Override
    public void onBillingError(int i, Throwable throwable) {

    }

    @Override
    public void onBillingInitialized() {

    }

    @Override
    public void onDestroy() {
        if (bp != null)
            bp.release();

        super.onDestroy();
    }
}

**Comment by onuryurtturk** [comment]
hey, I solved my problem with publishing on Google Play. Everything is working fine Thanks :)

**Comment by byhtada** [comment]
You publish Work version or testing?

**Comment by Farasy** [comment]
Publish as alpha or beta for testing.
