### ISSUE TITLE
It is not working with eclipse

### ISSUE THREAD

**Issue by tolgaytoklar** [anjlab/android-inapp-billing-v3#113]
Hi

I am using eclipse, i added the jar file to build path. But when i put this line to my activity:

implements BillingProcessor.IBillingHandler

I am getting "BillingProcessor cannot be resolved to a type" error. How can i fix it?

**Comment by cjserio** [comment]
You probably need to put the JAR in the "libs" folder of your project. Otherwise Android won't pay attention to it when you create an APK.
