### ISSUE TITLE
getPurchaseListingDetails() returns null

### ISSUE THREAD

**Issue by T-Rex96** [anjlab/android-inapp-billing-v3#114]
I'm trying to get the price of my IAP to display it in the app.

So mBillingProcessor.getPurchaseListingDetails("my.product.id").priceText; gives me a nullpointer exception.

mBillingProcessor.purchase(MainActivity.this, "my.product.id"); works though. What am I doing wrong?

**Comment by T-Rex96** [comment]
Weird, when called in an OnClickListener it works as intended:

findViewById(R.id.button1).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                SkuDetails sku = mBillingProcessor.getPurchaseListingDetails(iap1);
                Log.d("purchase", sku.priceText);
            }
        });

**Comment by klaszlo8207** [comment]
I got this nullpointer exception to. The probleme was: you have to add some time befoire calling those methods: I added 200 ms after initialized the BP.
