### ISSUE TITLE
High RAM use

### ISSUE THREAD

**Issue by MiscoGuy** [anjlab/android-inapp-billing-v3#115]
Has anyone looked into the RAM usage of this library?

It seems really high!

Following the tutorial procedure to set up as per tutorial (https://github.com/anjlab/android-inapp-billing-v3), I get a RAM usage of between 50MB to 80MB  taken up by com.android.vending. 

I am using the anjlab-iabv3-1.0.27.jar

Anyone experiencing this?

**Comment by serggl** [comment]
@MiscoGuy this library is lightweight...From you explanation seems line there is an issue inside google service itself?
