### ISSUE TITLE
Protect against attacks

### ISSUE THREAD

**Issue by biokys** [anjlab/android-inapp-billing-v3#118]
How to protect against Freedom attack now, after 15th of July?

**Comment by serggl** [comment]
Please refer to #108

On Wed, Sep 30, 2015 at 12:12 AM Jan Muller <notifications@github.com>
wrote:

> How to protect against Freedom attack now, after 15th of July?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anjlab/android-inapp-billing-v3/issues/118>.
>
-- 
Sergey, AnjLab
