### ISSUE TITLE
Best approach to load purchases before app starts

### ISSUE THREAD

**Issue by DVassilev** [anjlab/android-inapp-billing-v3#119]
Hello,

What's the best approach on getting purchases prior to the app starting? Would it be to make a launcher activity that starts the main activity once billing is initialised or perhaps something else?

Could I have you recommendations please?

Thanks,
Daniel

**Comment by DVassilev** [comment]
@serggl In addition, if I want to use the BillingProcessor across multiple activities what is the best approach? Do I just create a new one in each activity?

**Comment by serggl** [comment]
Thats up to you. I did createad new onces for each activities in my project
(which is not big)

On Wed, Sep 30, 2015 at 7:26 AM DVassilev <notifications@github.com> wrote:

> @serggl <https://github.com/serggl> In addition, if I want to use the
> BillingProcessor across multiple activities what is the best approach? Do I
> just create a new one in each activity?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anjlab/android-inapp-billing-v3/issues/119#issuecomment-144277788>
> .
>
-- 
Sergey, AnjLab

**Comment by DVassilev** [comment]
@serggl Ok, I suppose if it is lightweight enough. But do you have an answer to my first question above?

**Comment by DVassilev** [comment]
@serggl is it possible that onBillingInitialized doesn't get invoked?

**Comment by serggl** [comment]
@DVassilev my answer is `maybe yes` for your original question.
In my understanding `onBillingInitialized` wont be called if there are some issues with google play services on the device, so the library just could not connect to it
