### ISSUE TITLE
multidex with google play service lib

### ISSUE THREAD

**Issue by huongtran** [anjlab/android-inapp-billing-v3#121]
Dear you,

i am using android-inapp-billing-v3, but i have a problem error multidex : com/android/vending/billing/IInAppBillingService

i configed multiDexEnabled true but still can't resolve this problem, could you please help me or please suggest for me anything ?

thank you so much

tran

**Comment by serggl** [comment]
extend application class from MultiDexApplication?

On Tue, Oct 6, 2015 at 4:59 AM huongtran <notifications@github.com> wrote:

> Dear you,
>
> i am using android-inapp-billing-v3, but i have a problem error multidex :
> com/android/vending/billing/IInAppBillingService
>
> i configed multiDexEnabled true but still can't resolve this problem,
> could you please help me or please suggest for me anything ?
>
> thank you so much
>
> tran
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anjlab/android-inapp-billing-v3/issues/121>.
>
-- 
Sergey, AnjLab

**Comment by huongtran** [comment]
thank you for your support, i soloved problem, your lib is work very great, again thanks.
