### ISSUE TITLE
onBillingInitialised is never called

### ISSUE THREAD

**Issue by DVassilev** [anjlab/android-inapp-billing-v3#123]
Hi,

Is it possible that onBillingInitialised never gets called? If so, under what circumstances would this occur? I ask because my app waits for this to get called before doing anything and it seems for some users it's not working.

Thanks,
Daniel

**Comment by DVassilev** [comment]
@serggl Is this possible?

**Comment by serggl** [comment]
Possible, when library could not connect to google play services running on the device
