### ISSUE TITLE
Do not use float or double for money amounts

### ISSUE THREAD

**Issue by inktomi** [anjlab/android-inapp-billing-v3#124]
Internally, money amounts should always be parsed and stored as BigDecimal values. This allows clients to do math on the value correctly. SkuDetails can have a method to return a double to maintain api backwards compatibility, but internally prices should be a BigDecimal and it should also be available to clients.

For more information: http://programmers.stackexchange.com/questions/62948/what-can-be-done-to-programming-languages-to-avoid-floating-point-pitfalls

**Comment by Saketme** [comment]
Seconded this. I'm working at a company that makes financial products and we avoid using primitive types (float, double, etc.) for fields containing money amounts.

**Comment by inktomi** [comment]
I started work on this. Do we feel like this should be a breaking change, requiring devs to update their code to make the choice between long or the current Double -- or do you want to continue to return Double for priceValue?

I kind of don't like having the easy and obvious choice for price - priceValue - being the wrong one... but changing that will break the API for people (or worse, will return a long instead of a double).

**Comment by serggl** [comment]
Maybe you should just add new properties, leaving the old one in place?
People dont like breaking changes usually :)

On Thu, Oct 29, 2015 at 8:34 PM Matthew Runo <notifications@github.com>
wrote:

> I started work on this. Do we feel like this should be a breaking change,
> requiring devs to update their code to make the choice between long or the
> current Double -- or do you want to continue to return Double for
> priceValue?
>
> I kind of don't like having the easy and obvious choice for price -
> priceValue - being the wrong one... but changing that will break the API
> for people (or worse, will return a long instead of a double).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anjlab/android-inapp-billing-v3/issues/124#issuecomment-152259190>
> .
>
-- 
Sergey, AnjLab

**Comment by inktomi** [comment]
PR entered with updates as we discussed :)
