### ISSUE TITLE
NullPointer when doing getPurchaseListingDetails at onBillingInitialized

### ISSUE THREAD

**Issue by javiersantos** [anjlab/android-inapp-billing-v3#127]
I use this library to manage my InAppPurchases. To retrieve the items price I use `getPurchaseListingDetails(MY_SKU).priceText` on the `onBillingInitialized` method.

I noticed that sometimes it returns a NullPointerException:
```
Attempt to read from field 'java.lang.String com.anjlab.android.iab.v3.SkuDetails.priceText' on a null object reference
com.my.app.google.InAppPurchase$1.onBillingInitialized (InAppPurchase.java:70)
```

Is there another workaround to retrieve the items price once BillingProcessor is initialized?

**Comment by tpfaff** [comment]
I believe this is related to issue #126 . Issue 126 ultimately returns a null list of SKUDetails.

**Comment by javiersantos** [comment]
I fixed the issue by calling `priceText` only the first time that BillingProcessor is initialized.

**Comment by SuperThomasLab** [comment]
I need to call `priceText` four times when BillingProcessor is initialised. Some users of my app get the following crash. Any ideas?

    Caused by java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.anjlab.android.iab.v3.SkuDetails.h' on a null object reference
    com.superthomaslab.rootessentials.main_screen.MainActivity$11.onBillingInitialized (MainActivity.java:681)
    com.anjlab.android.iab.v3.BillingProcessor$1.onServiceConnected (BillingProcessor.java:93)
