### ISSUE TITLE
v1.0.28 not syncing with Gradle in Android Studio

### ISSUE THREAD

**Issue by ryan-simon** [anjlab/android-inapp-billing-v3#129]
Hey there,

I was adding the library to my build.gradle, and noticed that the library doesn't show up after syncing my dependencies.

The only way I was able to get the library to sync with Gradle was to use the previous version, 1.0.27.

I'm sure it's simple fix on your end. Let me know if you need any clarification. Thanks!

**Comment by serggl** [comment]
that's strange. Just tried and it works for me. Maybe you have an 'offline work' in gradle settings enabled?

**Comment by serggl** [comment]
I guess you need to add these lines to your gradle file:
```
allprojects {
    repositories {
        mavenCentral()
    }
}
```
