### ISSUE TITLE
(Suggestion) Gradle integration for Eclipse?

### ISSUE THREAD

**Issue by rotter** [anjlab/android-inapp-billing-v3#130]
Sorry for adding this as an "issue", since it's really a suggestion (I'd throw this as an email in a discussion group if there was any).

I dont know how hard it is for the gradle distribution to support both Android Studio and Eclipse, but if possible it would be awesome to be able to use the library using gradle on Eclipse. Right now you generate a "aar" file which afaik is not supported in Eclipse (I tried in the past for another lib and it didnt work) instead of using the good old jar format. It would be awesome if both files were available.

Best

**Comment by serggl** [comment]
you can export `jar` file that could be used in Eclipse with `./gradlew jarRelease` task

**Comment by rotter** [comment]
Yeah, Im using a jar already (a link to download the jar is included on the home of the project). But it would be much better if I could use gradle, but unfortunately the gradle link is AndroidStudio-only (aar file).

**Comment by serggl** [comment]
it should work without referencing `@aar` since `jar` artifact is also exported to maven central
