### ISSUE TITLE
Update relases

### ISSUE THREAD

**Issue by auchri** [anjlab/android-inapp-billing-v3#134]
Please add the missing releases to github: https://github.com/anjlab/android-inapp-billing-v3/releases :)

**Comment by jd-alexander** [comment]
Not sure if this is related. but I am having issues fetching the lib. Getting errors when it tries to download.

**Comment by leijdekkers** [comment]
Yep same here.....

**Comment by auchri** [comment]
@jd-alexander @leijdekkers Your problems are not related to my issue :)

However, I have the following in my build.gradle and it compiles fine:
`compile('com.anjlab.android.iab.v3:library:1.0.29') { transitive = true }`

**Comment by serggl** [comment]
added missed 1.0.29 release
