### ISSUE TITLE
Could not find library

### ISSUE THREAD

**Issue by saqsun** [anjlab/android-inapp-billing-v3#135]
Hi,

After your last commit you have changed things in build process and now I am getting this

Could not find library.aar (com.anjlab.android.iab.v3:library:1.0.29).
Searched in the following locations:
    https://repo1.maven.org/maven2/com/anjlab/android/iab/v3/library/1.0.29/library-1.0.29.aar

I have 
```
compile 'com.anjlab.android.iab.v3:library:1.0.+@aar'
```
in my dependencies. 

Everything was working before last commit.
I have attached contents of 1.0.28 and 1.0.29 so you can see the difference.
![screen shot 2015-12-07 at 12 09 09 pm](https://cloud.githubusercontent.com/assets/1752099/11622063/35fb0c70-9cd3-11e5-98af-064888dd82b1.png)
![screen shot 2015-12-07 at 12 09 28 pm](https://cloud.githubusercontent.com/assets/1752099/11622064/36378fb0-9cd3-11e5-8316-63787ae9dacc.png)

**Comment by ishratkhan** [comment]
I was facing same problem, but i changed
compile 'com.anjlab.android.iab.v3:library:1.0.+@aar' 
to
compile 'com.anjlab.android.iab.v3:library:1.0.27'

It works fine now,

**Comment by saqsun** [comment]
yep it is working when you do something like 
```
compile 'com.anjlab.android.iab.v3:library:1.0.29'
```
but I want it to use in 
```
compile 'com.anjlab.android.iab.v3:library:1.0.+@aar'
```
way to get updates automatically

**Comment by GaryHost** [comment]
Got the same problem, used ishratkhan solution, it seems to work fine...

**Comment by magicgoose** [comment]
Same problem, had to explicitly select .28 version, gradle for some reason tried to get .29 which is absent, I guess.

**Comment by serggl** [comment]
Seems like the `@aar` part is no longer needed. I will update README.
Should work both:
```
compile 'com.anjlab.android.iab.v3:library:1.0.29'
compile 'com.anjlab.android.iab.v3:library:1.0.+'
```

**Comment by saqsun** [comment]
Cool! 
Thanks.
