### ISSUE TITLE
Please ignore files

### ISSUE THREAD

**Issue by Volodar** [anjlab/android-inapp-billing-v3#138]
library/.classpath
library/.project
library/.settings/org.eclipse.jdt.core.prefs
library/project.properties
sample/.classpath
sample/.project
sample/.settings/org.eclipse.jdt.core.prefs
sample/project.properties

**Comment by inktomi** [comment]
I don't see these files in the project? Can you check again?

**Comment by serggl** [comment]
@Volodar haw about a PR?

**Comment by Volodar** [comment]
@serggl this files generated by the Eclipse

**Comment by serggl** [comment]
these were added to `.gitignore`
