### ISSUE TITLE
Error Authentication

### ISSUE THREAD

**Issue by ghost** [anjlab/android-inapp-billing-v3#139]
When i call bp.purchase(this, product_id);. It show dialog error "Authentication is required. you need to sign into your google account". How fix?

Thank you :)

**Comment by Coderlab** [comment]
Yes, I have the same error, I do not understand what to do.
Thanks

**Comment by vmihalachi** [comment]
Don't remember where I read it, but I think you need to upload the app on the play store first. At least that's how I fixed it. Then I have simply unpublished it and now nobody can download the app.

**Comment by inktomi** [comment]
You need to be testing with a release signed APK, and the versionCode must match something that has been released. 

You don't need to publish your updates to the beta channel or anything to test - but the versionCode that you're building locally needs to match something that has been published. You'll also need to be testing on a device that has the play store installed, and where the play store has been signed into an account.

(if that's the error you're getting..)

**Comment by serggl** [comment]
and you also need to log in into your gmail account on the test phone
