### ISSUE TITLE
Error while subscription

### ISSUE THREAD

**Issue by Swisyn** [anjlab/android-inapp-billing-v3#141]
I've generated a Yearly Subscription in Developer console, i've both purchasing and subscription in my app. 

The code is; 
 bp = new BillingProcessor(this, getString(R.string.key), getString(R.id.merchant_key), new BillingProcessor.IBillingHandler() {
            @Override
            public void onProductPurchased(String s, TransactionDetails transactionDetails) {

                Log.d("onProductPurchased", "> " +  bp.getPurchaseListingDetails("deal_reminder").isSubscription);
                Log.d("onProductPurchased", "> " +  bp.getPurchaseListingDetails("deal_remove_ads").isSubscription);

                if (!TextUtils.isEmpty(transactionDetails.purchaseInfo.responseData)) {
                    PurchaseInfo.ResponseData purchaseResponse = transactionDetails.purchaseInfo.parseResponseData();
                    if (purchaseResponse != null && purchaseResponse.purchaseState == PurchaseInfo.PurchaseState.PurchasedSuccessfully) {
                        Log.d("onProductPurchased", "> " + purchaseResponse.productId);

                        if (purchaseResponse.productId.equals("deal_reminder"))
                            isDealReminderHasBought = true;
                        else if (purchaseResponse.productId.equals("deal_remove_ads"))
                            isDealRemoveAdsHasBought = true;
                    }
                }
                if (isDealReminderHasBought)
                    Helper.showSnack(MainActivity.this, "Thank you for your support. Notification service activated.");
                else if (isDealRemoveAdsHasBought)
                    Helper.showSnack(MainActivity.this, "Thank you for your support. Ads are removed.");
            }

            @Override
            public void onPurchaseHistoryRestored() {
                //  KLog.w("Called");
            }

            @Override
            public void onBillingError(int errorCode, Throwable throwable) {
                switch (errorCode) {
                    case 0:
                        Log.d("onBillingError", "> Success - BILLING_RESPONSE_RESULT_OK");
                        break;
                    case 1:
                        Log.d("onBillingError", "> User pressed back or canceled a dialog - BILLING_RESPONSE_RESULT_USER_CANCELED");
                        break;
                    case 3:
                        Log.d("onBillingError", "> Billing API version is not supported for the type requested - BILLING_RESPONSE_RESULT_BILLING_UNAVAILABLE");
                        break;
                    case 4:
                        Log.d("onBillingError", "> Requested product is not available for purchase - BILLING_RESPONSE_RESULT_ITEM_UNAVAILABLE");
                        break;
                    case 5:
                        Log.d("onBillingError", "> Invalid arguments provided to the API. This error can also indicate that the application was not correctly signed or properly set up for In-app Billing in Google Play, or does not have the necessary permissions in its manifest - BILLING_RESPONSE_RESULT_DEVELOPER_ERROR");
                        break;
                    case 6:
                        Log.d("onBillingError", "> Fatal error during the API action - BILLING_RESPONSE_RESULT_ERROR");
                        break;
                    case 7:
                        Log.d("onBillingError", "> Failure to purchase since item is already owned - BILLING_RESPONSE_RESULT_ITEM_ALREADY_OWNED");
                        break;
                    case 8:
                        Log.d("onBillingError", "> Failure to consume since item is not owned - BILLING_RESPONSE_RESULT_ITEM_NOT_OWNED");
                        break;
                }

                //  Toast.makeText(MainActivity.this, Integer.toString(errorCode), Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onBillingInitialized() {
                bp.loadOwnedPurchasesFromGoogle();
                isDealReminderHasBought = bp.isPurchased("real_reminder");
                isDealRemoveAdsHasBought = bp.isSubscribed("deal_remove_ads");
            
    Log.d("isDealRemveAdsHasBought", "> " + isDealRemoveAdsHasBought);
                Log.d("isDealReminderHasBought", "> " + isDealReminderHasBought);
                Log.d("onProductPurchased", "> " +  bp.getPurchaseListingDetails("deal_reminder").isSubscription);
                Log.d("onProductPurchased", "> " +  bp.getPurchaseListingDetails("deal_remove_ads").isSubscription);
            }
        });

        bp.loadOwnedPurchasesFromGoogle();

Purchasing is Ok, working like a charm.

 But in subscription mode it says like; 
![Subscrition dialog](http://oi67.tinypic.com/aw2weo.jpg)
it acts like its daily subscription but its chosen yearly. 

in logcat; Payload mismatch: subs:deal_remove_ads != inapp:deal_remove_ads:70d11e1d-1979-45c8-8fd9-b9be0bda039c

the subscription id is; <strong>deal_remove_ads</strong> and calling it in method;   

bp.subscribe(MainActivity.this, "deal_remove_ads");

Is there something that i am missing?

**Comment by mzestars** [comment]
Don't worry, this only happen if u r using test account. If u use real account should be no issue.

**Comment by Swisyn** [comment]
@mzestars thank you so much for the quick response. So how can i test that is it working or not. Do you have any suggestions?

**Comment by mzestars** [comment]
You have to actually buy it using real money.

**Comment by Swisyn** [comment]
Thanks then gotta buy my own app :P

**Comment by jcdom** [comment]
"Note: Test subscription purchases recur daily, regardless of the product's subscription period."

This note is in the section "Test Purchases (In-app Billing Sandbox)" of this page:
http://developer.android.com/google/play/billing/billing_testing.html

I think that a subscription is recur daily for you can test the renewal.

**Comment by Swisyn** [comment]
@jcdom Thank you, i've not got an experience before i try subscription type. Now i see the explanation `Note: Test subscription purchases recur daily, regardless of the product's subscription period.`. First i've tested with it real money as @mzestars said and it worked. Now i tested with test account also it's working but i still can't figure it out why it wasn't working yesterday :P

**Comment by fafara** [comment]
Can I implement this for file download too?
