### ISSUE TITLE
Calling from React Native? Getting NULL object for SkuDetails with getPurchaseListingDetails

### ISSUE THREAD

**Issue by cbrevik** [anjlab/android-inapp-billing-v3#143]
There are no good alternatives for in app billing on React Native. I'd like to wrap your library, but I notice from another issue (#120) that at least the purchase-method should be called from the UI thread.

The thing is though, that primarily React Native modules will be called async on other threads. Many other libraries (like OpenIAB) are tightly coupled to being run on the UI thread (goes as far as throwing an exception if you do not), which does not play well with RN. 

Anyway, my question is;
Is this also the case for the other methods (i. e. UI thread only)? Before I got as far as testing purchasing, I made a dummy implementation trying to call `getPurchaseListingDetails`, but I keep getting a NULL object. 

When debugging it seems like the `RESPONSE_CODE` is 0, but `skuDetails.getStringArrayList(Constants.DETAILS_LIST)` returns an empty list.

Sample implementation here; https://github.com/idehub/iab-android-test/blob/master/android/src/main/java/com/idehub/IabTest/InAppBillingBridge.java

**Comment by jtv7** [comment]
I have the same error, except my issue returns Error 6.

**Comment by cbrevik** [comment]
Seems like this is might be because some issue I had with signing the apk, when I released a new apk to the beta channel it started working. Still weird I did not get an error response.
