### ISSUE TITLE
Can i attach developer payload when purchase?

### ISSUE THREAD

**Issue by durunvo** [anjlab/android-inapp-billing-v3#144]
When call purchase, can i attach some payload?

http://developer.android.com/google/play/billing/billing_integrate.html#Purchase

"developerPayload String is used to specify any additional arguments that you want Google Play to send back along with the purchase information."

**Comment by gaborauth** [comment]
Hi, I've made a patch and a pull request about it:
https://github.com/anjlab/android-inapp-billing-v3/pull/146

**Comment by durunvo** [comment]
Thank you so much, when it will be for next release?

**Comment by serggl** [comment]
merged
