### ISSUE TITLE
Got an error "Fatal Exception: java.lang.RuntimeException" 

### ISSUE THREAD

**Issue by conzorz** [anjlab/android-inapp-billing-v3#145]
Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=null, request=2061984, result=0, data=Intent { (has extras) }} to activity {com...}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
 
Caused by java.lang.NullPointerException
com.anjlab.android.iab.v3.BillingBase.getPreferencesBaseKey (BillingBase.java:37)
com.anjlab.android.iab.v3.BillingProcessor.getPurchasePayload (BillingProcessor.java:450)
com.anjlab.android.iab.v3.BillingProcessor.handleActivityResult (BillingProcessor.java:379)
com... (My call)

**Comment by bood** [comment]
Maybe try passing application context instead of activity to BillingProcessor?

**Comment by serggl** [comment]
closing this in flavour of #166
