### ISSUE TITLE
"developerPayload" does not exist when purchase is done on Chromebook devices

### ISSUE THREAD

**Issue by yukuku** [anjlab/android-inapp-billing-v3#147]
Using `getString` for getting `developerPayload` causes JSON exception when there is no `developerPayload`. 

It happens when using In-App Billing for Android Apps for Chrome (ARC) as mentioned here: https://developer.chrome.com/apps/arc_in_app_payments

> Note: Do not use payload strings when making purchase requests. ARC ignores them.

Replacing `getString` with `optString` resolves this problem.

**Comment by yukuku** [comment]
Edit: on ARC, developerPayload is always empty, so it should not even be constructed / sent.
If so, it will fail verification.

**Comment by serggl** [comment]
@yukuku are you interested in making PR with a fix for this?

**Comment by yukuku** [comment]
No, because Android Apps for Chrome (ARC) is somehow deprecated. It is being replaced by a new Android runtime.
