### ISSUE TITLE
Missing BILLING_RESPONSE_RESULT_SERVICE_UNAVAILABLE in Constants class.

### ISSUE THREAD

**Issue by yukuku** [anjlab/android-inapp-billing-v3#148]
`public static final int BILLING_RESPONSE_RESULT_SERVICE_UNAVAILABLE = 2;` should be in `Constants`.

**Comment by serggl** [comment]
how about a PR?

On Thu, Jan 21, 2016 at 12:22 PM yukuku <notifications@github.com> wrote:

> public static final int BILLING_RESPONSE_RESULT_SERVICE_UNAVAILABLE = 2;
> should be in Constants.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anjlab/android-inapp-billing-v3/issues/148>.
>
-- 
Sergey, AnjLab

**Comment by yukuku** [comment]
PR: #149

**Comment by serggl** [comment]
merged
