### ISSUE TITLE
DF-PPA-10 Error

### ISSUE THREAD

**Issue by kristijandraca** [anjlab/android-inapp-billing-v3#150]
So, I use this library as shown in example, create new gmail acc for testing. Add that testing account under "Gmail accounts with testing access", add new apk file to Dev console and everything, and finally wait next day. 

When I try to make purchase, I can see dialog with label that it's for testing, and when I add my Visa, it return DF-PPA-10 Error. (App returns response code 2 BILLING_RESPONSE_RESULT_SERVICE_UNAVAILABLE)

When I try to use same Visa on any other app, it works fine. Does anyone know how to fix this?

**Comment by afollestad** [comment]
Same problem here. That error code means it had a problem contacting the server, but that shouldn't be an issue.
