### ISSUE TITLE
signature is null, when invoke billingProcessor.getSubscriptionTransactionDetails(productId)

### ISSUE THREAD

**Issue by demonito** [anjlab/android-inapp-billing-v3#151]
Hello!

I've faced with strange thing. Let's imagine that I have subscribed, but backend couldn't check subscrition in some reasons at that moment. Then, if I later invoke billingProcessor.getSubscriptionTransactionDetails(productId), the returned TransactionDetails contains empty (null) signature. If I try to make subscription again (using billingProcessor.subscribe()), I get an error "You are already subsribed to <subscription_name>". So, I must cancel subscription and subscribe to it again.

**Comment by smail2133** [comment]
Same issue, getSubscriptionTransactionDetails returns null. But subscription already subscribed.

**Comment by waldo9** [comment]
I get the same issue!
If I subscribe on one device, it works perfectly, I get the transaction details.
But as soon as I switch to another device (I have the same Google account signed in and I can see the sub in Google Play), the getSubscriptionTransactionDetails returns null. Can anybody help me with this?
