### ISSUE TITLE
Permanent error 110

### ISSUE THREAD

**Issue by mysho87** [anjlab/android-inapp-billing-v3#152]
I have real products. All tests in real applications for real money. For each purchase you get this error.

```
D/iabv3﹕ resultCode = -1, responseCode = 0
[ERROR] onBillingError, errorCode: 110
```

**Comment by ryan-simon** [comment]
Running into this same issue @mysho87. Did you find a solution?

**Comment by mysho87** [comment]
Sorry, but then I used original google tutorial :(

**Comment by kriti-1** [comment]
@RyanSimon Did you find solution for this. Even am running in same problem

**Comment by jangrewe** [comment]
I had the same problem, because i tried to buy an item again without consuming it before!

Fails: purchase, purchase
Works: purchase, consume, purchase, consume, purchase

My solution:
```
@Override
public void onProductPurchased(@NonNull String productId, @Nullable TransactionDetails details) {
    bp.consumePurchase(productId);
}
```
