### ISSUE TITLE
What is the correct way to get expiry date of subscription?

### ISSUE THREAD

**Issue by re3lex** [anjlab/android-inapp-billing-v3#153]
Hi, first of all thanks for useful lib!
I have question: I'm getting Transaction details and purchaseInfo but there is no expiryDate of subscription.

What is the best way to get it? Could developers add such functionality to this library?

**Comment by tapankumar** [comment]
Hi,

I have exactly same issue.

Can anyone give any hint on this?

**Comment by SakthivelA** [comment]
Hi,
    I have the same issue.

Can anyone give solution or hint.

**Comment by serggl** [comment]
you need to call `getSubscriptionTransactionDetails` it will give you a `purchaseTime`. You will need to add subscription time and calculate the end date by yourself
