### ISSUE TITLE
library not initialise when create new BillingProcessor()

### ISSUE THREAD

**Issue by durunvo** [anjlab/android-inapp-billing-v3#154]
library is not initialise when create new BillingProcessor(), but initialise after call purchase first time 
<img width="377" alt="screen shot 2559-02-12 at 1 37 31 pm" src="https://cloud.githubusercontent.com/assets/5458194/13000530/c8eab7c6-d18d-11e5-98f4-cc4c52040b0d.png">

action down is when i press buy button, it will call purchase.

what should i do?

**Comment by serggl** [comment]
@rubengees 👍 thats correct
