### ISSUE TITLE
Refunded orders are not being considered?

### ISSUE THREAD

**Issue by rotter** [anjlab/android-inapp-billing-v3#155]
After I refunded someone for a non-consumable IAP, the person lost access to the IAP. Maybe the refunded purchases are not being considered as normal/valid purchases? Can anyone confirm?

I tried checking the code but didnt find any part that considers exclusively the purchase state 1 (successful purchase) and not the state 3 (refunded).

**Comment by eldariof** [comment]
I confirm issue and I think that it is defect. No ways for detect Refunded status. Furthermore Refunded status never could return - need to rid from this status in library or fix issue.

**Comment by serggl** [comment]
details on refunds were discussed here #44
