### ISSUE TITLE
BILLING_RESPONSE_RESULT_ERROR & BILLING_ERROR_FAILED_TO_INITIALIZE_PURCHASE - How do you troubleshoot these?

### ISSUE THREAD

**Issue by jkane001** [anjlab/android-inapp-billing-v3#157]
I don't see any way of knowing what causes this error, but I'm seeing a lot of them when I'm running my app with this library in production. In all cases so far, I've not seen the error object be anything but null, so I don't know what to do to solve these issues. Is there anything I can do to get to the root of these issues?

**Comment by allentcm** [comment]
http://stackoverflow.com/a/19181915/4423941
