### ISSUE TITLE
Owned plan return responseCode 6 not 7

### ISSUE THREAD

**Issue by mtrakal** [anjlab/android-inapp-billing-v3#160]
When I have subscription and try to buy same subscription, dialog from Google Play show: 

> You're already subscribed to...

But after `com.anjlab.android.iab.v3:library:1.0.31` return: `responseCode = 6` when I look to Constants:
`BILLING_RESPONSE_RESULT_ERROR =    6;              //Fatal error during the API action`

But it should (I think) return: `BILLING_RESPONSE_RESULT_ITEM_ALREADY_OWNED = 7; //Failure to purchase since item is already owned`

**Comment by serggl** [comment]
These are Google Play managed errors, this library just forwards them through
