### ISSUE TITLE
Error 102 after first try of purchase

### ISSUE THREAD

**Issue by archiewahwah** [anjlab/android-inapp-billing-v3#163]
If I purchase the product at first time, I got error 102. If I press again it works well

code is

    public class InAppActivity extends Activity {

    private BillingProcessor bp;
    private static final String PRODUCT_ID = "android.test.purchased";
    private static final String LICENSE_KEY = "";
    private static final String MERCHANT_ID=null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.inapp_activity);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);

        Button purchase = (Button) findViewById(R.id.purchase);

        bp = new BillingProcessor(this, LICENSE_KEY, MERCHANT_ID, new BillingProcessor.IBillingHandler() {

            @Override
            public void onProductPurchased(String productId, TransactionDetails details) {
                showToast("onProductPurchased: " + productId);
                Log.d("inAppActivity", "consumed");
            }
            @Override
            public void onBillingError(int errorCode, Throwable error) {
                showToast("onBillingError: " + Integer.toString(errorCode));
            }
            @Override
            public void onBillingInitialized() {
                showToast("onBillingInitialized");

            }
            @Override
            public void onPurchaseHistoryRestored() {
                showToast("onPurchaseHistoryRestored");
            }
        });

        purchase.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                bp.purchase(InAppActivity.this, PRODUCT_ID);
                bp.consumePurchase(PRODUCT_ID);
            }
        });

        }

    private void showToast(String message) {
        Toast.makeText(this, message, Toast.LENGTH_LONG).show();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (!bp.handleActivityResult(requestCode, resultCode, data))
            super.onActivityResult(requestCode, resultCode, data);
    }

}

Im I doing something wrong ?

**Comment by Ashish-Bansal** [comment]
Hey, I'm not really sure but I think error is in line where you used bp.consumePurchase. As purchase is async, so you are trying to consume it even before purchasing. Try to consume purchase in onProductPurchased callback.

**Comment by serggl** [comment]
seem like you need to use non-empty `LICENSE_KEY`

**Comment by surenderkhowal** [comment]
Same here! If I subscribe the product, I got error 102.

**Comment by Joisar** [comment]
I'm facing the same issue.

**Comment by Deepak-Ganachari** [comment]
Did anybody solved this issue, I am facing the same , is it happening for test purchase ? bcoz i am using test purchase ?

**Comment by xitize** [comment]
https://stackoverflow.com/a/46660662/3139621  solved
