### ISSUE TITLE
Error: This version of the application is not configured for billing

### ISSUE THREAD

**Issue by WaKeMaTTa** [anjlab/android-inapp-billing-v3#171]
**I need some help**. Get this error:

![image](https://cloud.githubusercontent.com/assets/3450257/14882364/b955f028-0d38-11e6-89ce-2df786ea4b73.png)

```
Error: This version of the application is not configured for billing through Google Play. Check the help center form more information.
```

**Comment by fjanicki** [comment]
Check this out: http://stackoverflow.com/questions/11068686/this-version-of-the-application-is-not-configured-for-billing-through-google-pla/22469253#22469253

**Comment by WaKeMaTTa** [comment]
Thanks.
