### ISSUE TITLE
(+) warning and use the library in the fragments

### ISSUE THREAD

**Issue by VanitarNordic** [anjlab/android-inapp-billing-v3#172]
Fist, Gradle gives a warning of using "+" inside the gradle library name.

Second, how can I use it inside a fragment?

**Comment by WaKeMaTTa** [comment]
What is the version of Gradle are you using? And what version of SDK are using?

**Comment by VanitarNordic** [comment]
I compile it on SDK 23.
Build tools version 23.0.3
I am not quite sure about gradle version but it is the last version on Android Studio 2.1

**Comment by WaKeMaTTa** [comment]
I have the same version than you, and i don't get this error. :confused:

**Comment by VanitarNordic** [comment]
That's not an error, it gives a warning of not using (+) inside the gradle library name.

Another issue was that how we can use the code inside fragments?

**Comment by serggl** [comment]
instead of (+) use a concrete version if library. (+) was referenced in README as a 'quick start guide', you should avoid using it in your app
