### ISSUE TITLE
Help - What is onActivityResult

### ISSUE THREAD

**Issue by WaKeMaTTa** [anjlab/android-inapp-billing-v3#173]
Someone can explain me what do the function `onActivityResult`. Please.

```java
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
  if (!bp.handleActivityResult(requestCode, resultCode, data))
    super.onActivityResult(requestCode, resultCode, data);
}
```

**Comment by voidstarfire** [comment]
Looks like it's broken, it's never being called anymore.

When an activity receives a result from a source (can be multiple things) in this case it's from the IAP billing response.

So this method is called when say we get a list of products (I can't get it to work on this library).

**Comment by WaKeMaTTa** [comment]
Thanks for the response. 

Where i need to execute some function when **user successfully purchase**?

**Comment by voidstarfire** [comment]
I'm not sure anymore, I'm making my own library cause this is broken. Just follow this guide:
http://developer.android.com/google/play/billing/billing_integrate.html#billing-add-aidl

**Comment by WaKeMaTTa** [comment]
Okey. Thanks.

**Comment by jcoleman2005** [comment]
If using debug (android.test.purchased), does onActivityResult trigger?
Seems like its not getting triggered at all
