### ISSUE TITLE
How to handle mutilple activities?

### ISSUE THREAD

**Issue by ursusursus** [anjlab/android-inapp-billing-v3#175]
How do you suggest handling iab when using multiple activities which would need to use BillingProcessor? I see you bind to google play service in constructor so I imagine if using if in my DetailActivity would be wasteful since its created often.

Thanks

**Comment by MaximilianKeppeler** [comment]
I made a base class, which implements this IAP stuff. In every Activity, where I need IAPs, I extend from this billing base class.

**Comment by ursusursus** [comment]
Thats okay, I just want to go around the binding everytime..

**Comment by serggl** [comment]
seem like you need a singleton class initiated from the `Application` class. Solution made by @MaximilianKeppeler is also good

**Comment by ursusursus** [comment]
Well that seems like a waste, imagine activity with list feed and detail activity where user both back and forth often.

Yea, refcounted singleton seems like a good solution
