### ISSUE TITLE
E/iabv3: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode

### ISSUE THREAD

**Issue by S1m0n3** [anjlab/android-inapp-billing-v3#177]
I'm trying my app with in app purchase, but when I call bp.purchase(MainActivity.this, PRODUCT_ID); i get following messages in logcat:

E/iabv3: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
D/LOG: onBillingError: 110

**Comment by Trikke** [comment]
private static final int PURCHASE_FLOW_REQUEST_CODE = 2061984;

i assume this is the problem. Can the dev correct this?

**Comment by conzorz** [comment]
Yep. This is preventing me updating my app as purchases just don't work. Any way to specify a lower version of library to fix for now? It's on 1.0.31, and 1.0.30 doesn't seem to work either...

**Comment by serggl** [comment]
PR #178 was merged and released to maven central, so closing this

**Comment by dfabulich** [comment]
Mysteriously, I got this error in production on an app running 1.0.25. Upgrading to the latest 1.0.43 magically fixed it. 🎩
