### ISSUE TITLE
which method checks for cancelled purchases?

### ISSUE THREAD

**Issue by rainman20** [anjlab/android-inapp-billing-v3#180]
when the billing fails or cancelled by the user, which method is called?
for example, the user clicks on "purchase button" and then decides to cancel. Is there a way to check for that?

**Comment by RubicCube** [comment]
don't miss to add to your activity
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (!bp.handleActivityResult(requestCode, resultCode, data))
            super.onActivityResult(requestCode, resultCode, data);
}
then from here: https://github.com/anjlab/android-inapp-billing-v3/pull/176/files
you can handle response from "onBillingError()" => errorCode = 1

**Comment by rainman20** [comment]
I did a toast onbilling error: 
```
@Override
            public void onBillingError(int errorCode, Throwable error) {
                showToast("something happened");
            }
```
but the message is not shown when the user dismiss the purchase box (clicks return or etc)

**Comment by RubicCube** [comment]
don't miss to add to your activity
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
if (!bp.handleActivityResult(requestCode, resultCode, data))
super.onActivityResult(requestCode, resultCode, data);
}
it should work (please add Log not Toast)

**Comment by rainman20** [comment]
@RubicCube 
yes, I have added that method
also in logocar I get this
`[1] com.google.android.finsky.billing.lightpurchase.PurchaseFragment.a(29147): Purchase failed: PurchaseError{type=3 subtype=0}`
but I want to show a toast to user that say it failed

**Comment by RubicCube** [comment]
You can logging response message, but not showing on Toast, right?
You always show Toast in ui thread like this:

getActivity().runOnUiThread(new Runnable() {
    @Override
        public void run() {
        }
}
