### ISSUE TITLE
Get feedback when purchase has been made

### ISSUE THREAD

**Issue by progrmor** [anjlab/android-inapp-billing-v3#181]
Hi. I'm trying out this library but would need some help with something. Is there a way of receiving a "flag" for when a purchase has been made? I need to make graphical changes if that happens to showcase that they have ownership of the product in question.

**Comment by AlexioVay** [comment]
Did you try this method?

```
    @Override
    public void onProductPurchased(String productId, TransactionDetails details) {
        // Your Code
    }
```

**Comment by progrmor** [comment]
I have had a look at that yes, I need a method that continuously check for purchases, not sure if this method does so. Example: When a purchase has been made, I want immediate response when the purchase has gone through to make a graphical change. I don't want to have to re-build the activity to notice a change in the onProductPurchased method. Perhaps this method does so, I don't know cause I haven't managed to accomplish this behavior.

**Comment by AlexioVay** [comment]
I check if a product have been bought this way:

```
            if (bp.isPurchased(PRODUCT_ID) || bp.isPurchased(PRODUCT_ID_ULTIMATE)) {
                editor.putBoolean("premium", true);
                editor.apply();
            }
```

And in my case PRODUCT_ID is this for example:

`    private static final String PRODUCT_ID = "com.vaydesign.thewitcher3.removeads";`

The method I suggested in my post before is called right after the purchase, but you asked for "continously check", so this one here should be the method you need?

**Comment by progrmor** [comment]
That might just be it! Thanks!

**Comment by progrmor** [comment]
Ran into a problem straight away, sorry. But where do you check this statement? There's no method for checking statements during runtime?

**Comment by joshid** [comment]
The method onProductPurchased(String productId, TransactionDetails details) is the same for getting feedback on suscriptions?

**Comment by serggl** [comment]
@AlexioVay answer is correct. `bp.isPurchased` was designed for these purposes
