### ISSUE TITLE
Check whether in-app product purchased or not while offline

### ISSUE THREAD

**Issue by huldrer** [anjlab/android-inapp-billing-v3#182]
When I'm trying to create new BillingProcessor when device is offline, it throws Billing error and Billing is not initialized.
For example, user already bought an in-app product and I want to give him access to that product even when his device is offline. I suppose information about purchases is stored in some kind of cache on a device.
Is there any way to check whether in-app product purchased or not when there's no Internet connection?
Thanks a lot for your library!

**Comment by scottyab** [comment]
> Is there any way to check whether in-app product purchased or not when there's no Internet connection?
There isn't as far as I'm aware in via the Google Play Billing API. You'd need to persistent an additional flag/value on device to say the user has this product. Maybe you'd expire it after a certain amount of time?

**Comment by trans** [comment]
> Because the Google Play client now caches In-app Billing information locally on the device, you can use the Version 3 API to query for this information more frequently, for example through a getPurchases call. Unlike with previous versions of the API, many Version 3 API calls will be serviced through cache lookups instead of through a network connection to Google Play, which significantly speeds up the API's response time. 

https://developer.android.com/google/play/billing/api.html

**Comment by serggl** [comment]
@trans in my understanding that info is cached once you made any billing API calls while online, otherwise you'll get an error

**Comment by BilalAsif25** [comment]
You should use Shared Preferences, When the Purchase is Successful. Set Boolean variable to true, and use that variable to check either its false to show ads, if not then your logic. Hope that help.
