### ISSUE TITLE
Some devices are crashing getPurchaseListingDetails

### ISSUE THREAD

**Issue by franciscofranco** [anjlab/android-inapp-billing-v3#183]
Non-fatal Exception: org.json.JSONException: Value auto.repeat.LP of type java.lang.String cannot be converted to JSONObject
       at org.json.JSON.typeMismatch(JSON.java:111)
       at org.json.JSONObject.(JSONObject.java)
       at org.json.JSONObject.(JSONObject.java)
       at com.anjlab.android.iab.v3.BillingProcessor.loadPurchasesByType(SourceFile:170)
       at com.anjlab.android.iab.v3.BillingProcessor.loadOwnedPurchasesFromGoogle(SourceFile:187)
       at com.anjlab.android.iab.v3.BillingProcessor$1.onServiceConnected(SourceFile:93)

I simply call loadOwnedPurchasesFromGoogle()

I can't reproduce on my devices, but some users trigger it somehow.

**Comment by kaio37k** [comment]
Hey, could you please link your class? I have no idea how to use this library and there is no support :P

**Comment by franciscofranco** [comment]
Link my class for what? The steps on the readme are enough to set it up.

**Comment by serggl** [comment]
@franciscofranco do you still face these issues?

**Comment by franciscofranco** [comment]
Not sure. This issue is a bit random. Usually had it if I called this a second time after setting up billing. Kinda hard to reproduce.

**Comment by serggl** [comment]
@franciscofranco `auto.repeat.LP` (from the stack trace) is this your product ID?

**Comment by serggl** [comment]
This is quite odd, since according to the stack trace billing service returned not a JSON, but the docs say that [it should be JSON] (https://developer.android.com/google/play/billing/billing_reference.html#getPurchases)
So...not sure what could be done here

**Comment by franciscofranco** [comment]
auto.repeat.LP is not my productId, I have no clue what it is. Without looking at your code maybe you can wrap it in a try & catch just to prevent the FC and then log the exception. Or check for the object instance and do whatever based on what it is. I know it says it should be JSON but hey, it's Google we're talking about here :p

**Comment by serggl** [comment]
well, its already in a try & catch :) If this is not a JSON string, but some random string instead (like `auto.repeat.LP`) then there is nothing that could be done here.
So now Im concerned that library works ok for this case. Could it be a 'Freedom' like attack?

**Comment by franciscofranco** [comment]
Maybe Freedom... I'm not sure. Nevertheless I'll re-open this if I see it again! Thanks.
