### ISSUE TITLE
Issue with play service 9.2?

### ISSUE THREAD

**Issue by gemiren** [anjlab/android-inapp-billing-v3#186]
I just updated my app to play service 9.2 and then got feedback from users that in app purchase failed. Does anyone have this problem? This awesome lib worked so well for me before. Thanks.

**Comment by Neferetheka** [comment]
Same issue for me.
Looks like the issue is the PURCHASE_FLOW_REQUEST_CODE in the BillingProcessor class.
I've this log:

iabv3: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode

**Comment by AlexioVay** [comment]
What do you compile in your gradle? I'm using 9.2 too and it works fine.

Like this:

```
    compile 'com.google.android.gms:play-services:9.2.0'
    compile 'com.google.android.gms:play-services-ads:9.2.0'
    compile 'com.google.android.gms:play-services-gcm:9.2.0'
    compile 'com.google.android.gms:play-services-analytics:9.2.0'
```

**Comment by gemiren** [comment]
I'm using the same gradle setup. Maybe it's an one time issue. I got reports from users earlier this week that the in-app biling not working but it seems to be working again since yesterday.

**Comment by AlexioVay** [comment]
So, do you receive inapp-purchases? Because now I'm worried too if some devices won't work maybe.

**Comment by gemiren** [comment]
Yes, it seems working fine now. Not sure what happened. Thanks.
