### ISSUE TITLE
serviceConnection never called in AVD

### ISSUE THREAD

**Issue by mtrakal** [anjlab/android-inapp-billing-v3#188]
`compile 'com.anjlab.android.iab.v3:library:1.0.32'`

we call `mBillingProcessor = new BillingProcessor(this, Config.PLAY_API_KEY, this);` in Activity.

but never get some result from AIB to our activity.
I track code to [`bindPlayServices()`](https://github.com/anjlab/android-inapp-billing-v3/blob/master/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java#L112)

```
private void bindPlayServices() {
		try {
			Intent iapIntent = new Intent("com.android.vending.billing.InAppBillingService.BIND");
			iapIntent.setPackage("com.android.vending");
			getContext().bindService(iapIntent, serviceConnection, Context.BIND_AUTO_CREATE);
		} catch (Exception e) {
			Log.e(LOG_TAG, "error in bindPlayServices", e);
		}
	}
```

where is parameter [`serviceConnection`](https://github.com/anjlab/android-inapp-billing-v3/blob/master/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java#L116). I put breakpoints to [`onServiceDisconnected`](https://github.com/anjlab/android-inapp-billing-v3/blob/master/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java#L80) and [`onServiceConnected`](https://github.com/anjlab/android-inapp-billing-v3/blob/master/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java#L85) but it's never called :cry: .

Windows 10 x64,
latest SDK and AVD (Android Virtual Device) 25.1.7, API 23 Marshmallow 6.0,
tested on AVD with real Google account connected.

**Comment by serggl** [comment]
in-app purchases dont work on emulators
