### ISSUE TITLE
Add short SkuDetails title possibly?

### ISSUE THREAD

**Issue by diceroll123** [anjlab/android-inapp-billing-v3#189]
The `title` variable in SkuDetails looks something like `One Dollar (App Name)`

I'm suggesting, perhaps make a "short title" variable that removes the ` (App Name)`, just so you can get the IAP's object title _only_.

I don't know if the IAP API returns something like this so here's a quickly thrown-together way to do it. :stuck_out_tongue: 

```java

shortTitle = title.substring(0, title.lastIndexOf(" ("));
```

**Comment by serggl** [comment]
@diceroll123 you can contribute with a PR ;)

**Comment by romulus85** [comment]
Hi!
Doing that I am getting a crash report that seems that the title of the products do not follow always the same pattern:
```
Fatal Exception: java.lang.StringIndexOutOfBoundsException
String index out of range: -1
```
I can protect my code with something like:
```
            // Remove all between " ( name of app )"
            String productTitle = product.getTitle();
            int index = productTitle.indexOf(" (");
            if(index != -1)
            {
                productTitle = productTitle.substring(0, index);
            }
```
But then I have no idea what is being showed as title of the product.You have a clue what is this happening in certain devices?
