### ISSUE TITLE
checking if a product is purchased or not?

### ISSUE THREAD

**Issue by sagarrishabh** [anjlab/android-inapp-billing-v3#194]
how can I check if a product is purchased or not? I'm not getting how to use bp.loadOwnedPurchasesFromGoogle();    Moreover when  onPurchaseHistoryRestored() is called?

**Comment by flameboy** [comment]
You can check if a product is purchased with this condition:
```
if(bp.isPurchased("YOUR_PRODUCT_ID")) {
     doSomething();
}
```

**Comment by sagarrishabh** [comment]
hey thanks :)
