### ISSUE TITLE
3 seconds pause on the first initialization.

### ISSUE THREAD

**Issue by saeed-fri** [anjlab/android-inapp-billing-v3#195]
Hi,
Thanks for your great library, It's the best :+1: 

The only issue I have with it is that when I install the app for the first time, after creating the first BillingProcessor object my app stops working for 3 to 4 seconds. it happens only and only when I create the BillingProcessor for the first time (in the first installation).
the constructor doesn't take that time! apparently something happens afterward that blocks the main thread.

Thanks for your awesome library and your attention.

**Comment by Slamper** [comment]
maybe related to the blocking call in #191

**Comment by serggl** [comment]
yes, seems like its about #191
