### ISSUE TITLE
Subscription Order ID not updated with the suffix after first recurrence payment

### ISSUE THREAD

**Issue by joselufo** [anjlab/android-inapp-billing-v3#197]
After checking the [Google Play billing v3 payment documentation](https://developer.android.com/google/play/billing/billing_subscriptions.html#payment), Google says that they are gonna update the **orderId** field in the TransactionDetail JSON Object (**INAPP_PURCHASE_DATA**) with the suffix "..0", "..1", "..2", etc...

I created a weekly subscription SKU product (**NO TESTING ACCOUNT**) and paid the subscriptions just to verify how works the suffix to be able to do some logic behind.

My surprise is after one week and renewed the subscription. Google Play Billing still give me the base orderId without suffix and the purchase time is the original one and not the purchased time, where I renewed the subscription but, in the email that Google send with the transaction detail appear the orderId with the suffix and the order time updated. 

Why I'm not getting this information via GooglePlay Billing library? Caching?

**Comment by serggl** [comment]
maybe because of old Google Play Services version?

**Comment by dmhood** [comment]
This is happening with me as well, using the correct play services.

**Comment by Capyvara** [comment]
Having this problem as well, have you found a solution?

**Comment by serggl** [comment]
Does not seem to be related with this library itself.

**Comment by autonomousapps** [comment]
Due to inactivity, I am closing this issue. Feel free to re-open it if you have new information.
