### ISSUE TITLE
How tu use dummy SKUs like "android.test.purchased"?

### ISSUE THREAD

**Issue by ursusursus** [anjlab/android-inapp-billing-v3#201]
Hi, 
im trying to switch from IabHelper to this library.  However I see no way to use dummy skus to validate purchase success behaviour.

What I did before was use "android.test.purchased" as product id (sku) in purchase() and I would comment out the verification in Security.verifyPurchase and returned true as not to check the keys, because then even dummy-successful purchase would end in error..

Any way around this verification error for debug purpouses with this library?

**Comment by Pitel** [comment]
Same problem, same workaround.

I'd also like to use `android.test.purchased` in this library.
