### ISSUE TITLE
Authentication is required error 

### ISSUE THREAD

**Issue by snijsure** [anjlab/android-inapp-billing-v3#202]
I have integrated this library into my app. I always get following error dialog when I try to any kind of query.

Note my application version says 1.0.6.123 and that application has been "published" to google play store , alpha channel. Also when I am running this application, I have made sure it is being signed using release key and not debug key, but I still get this error.

I have done the "recommended" thing of resetting the phone, adding the account and the error still persist, anybody else seen this error?

![screen shot 2016-09-25 at 11 40 07 am](https://cloud.githubusercontent.com/assets/1580689/18817432/f083f408-8314-11e6-9ad9-3d80045e6064.png)

One other question of API

How do I find if user has already purchased an item, should one be using this API, after invoking loadOwnedPurchasesFromGoogle()?
 
    `bp.getPurchaseTransactionDetails("Product-ID");`

And if getPurchaseTransactionDetail returns non-null value its safe to declare that product has been purchased?

**Comment by turbo124** [comment]
+1

**Comment by frankyxcs** [comment]
You must use another google account to test the payment - not your developer account ! Once you have setup the library and correctly signed your apk it should work without any problems.

**Comment by serggl** [comment]
👍 for @frankyxcs recommendations

**Comment by avipars** [comment]
I had to remove my main google account (developer one) from the phone and then it works.
