### ISSUE TITLE
why purchaseInfo.parseResponseData() got private on new update? What is it's alternative?

### ISSUE THREAD

**Issue by Swisyn** [anjlab/android-inapp-billing-v3#211]
bp = new BillingProcessor(this, getString(R.string.key), getString(R.string.merchant_id), new BillingProcessor.IBillingHandler() {
            @Override
            public void onProductPurchased(String s, TransactionDetails transactionDetails) {
                if (!TextUtils.isEmpty(transactionDetails.purchaseInfo.responseData)) {
                    PurchaseInfo.ResponseData purchaseResponse = transactionDetails.purchaseInfo.parseResponseData();
                    if (purchaseResponse != null && purchaseResponse.purchaseState == PurchaseInfo.PurchaseState.PurchasedSuccessfully) {
                        if (purchaseResponse.productId.equals(DEAL_REMOVE_ADS)) {
                            if (subscriptionListener != null)
                                subscriptionListener.onSubscriptionDataLoaded(DEAL_REMOVE_ADS, true);

                            Helper.showSnack(MainActivity.this, getString(R.string.remove_ads_subscription_successful));
                        }

                        AnswersLogger.logPurchase(new PurchaseEvent()
                                .putItemPrice(java.math.BigDecimal.valueOf(4.99))
                                .putCurrency(java.util.Currency.getInstance("TRY"))
                                .putItemName("Remove Ads")
                                .putItemType("Subscription")
                                .putItemId(DEAL_REMOVE_ADS)
                                .putSuccess(true));
                    }
                }
            }

            @Override
            public void onPurchaseHistoryRestored() {
            }

            @Override
            public void onBillingError(int errorCode, Throwable throwable) {
                
            }

            @Override
            public void onBillingInitialized() {
                bp.loadOwnedPurchasesFromGoogle();

                if (subscriptionListener != null)
                    subscriptionListener.onSubscriptionDataLoaded(DEAL_REMOVE_ADS, bp.isSubscribed(DEAL_REMOVE_ADS));

            }
        });

**Comment by serggl** [comment]
the answer is: `purchaseInfo.purchaseData`. Sorry for setting this private, I should better put a deprecation notice

**Comment by serggl** [comment]
addressed in 1.0.36
