### ISSUE TITLE
`null` SkuDetails result from `getPurchaseListingDetails`

### ISSUE THREAD

**Issue by RishabhTayal** [anjlab/android-inapp-billing-v3#214]
I am getting null response when I call `bp.getPurchaseListingDetails(MY_PRODUCT_ID);`. Any help?

**Comment by RishabhTayal** [comment]
I figured it out. I was calling this method in `onCreateView`. At this instance the `onBillingInitialized()` was not called back. I had to wait until `onBillingInitialized` is called.

**Comment by rohitrt89** [comment]
Yes Rishabh you are saying right, we have to wait untill onBillingInitializes is called and then bp.getPurchaseListingDetails(MY_PRODUCT_ID) will return SkuDetails object.

**Comment by mabdullahrafique** [comment]
I am calling this method on BillingInitialized but the same error is occuring
