### ISSUE TITLE
Question: how do I know if the payment didn't get charged?

### ISSUE THREAD

**Issue by albionh** [anjlab/android-inapp-billing-v3#215]
I have posted a question on [stackoverflow ](http://stackoverflow.com/questions/40671879/google-in-app-billing-v3-handle-cancel-managed-product) and no one has posted anything yet, so I figured it might be better to ask here as well.

What I want to know if there's a way I can get the status of the payment after the user purchases it. If it's declined (or cancelled for other reason), I don't want to issue the digital content to the user.

I have tried using `loadOwnedPurchasesFromGoogle` and `getPurchaseTransactionDetails(PRODUCT_ID).purchaseInfo.purchaseData.purchaseState` to see if I can get the new status of the purchase. I also tried checking the purchase state right after the user purchases the product:
`PurchaseState state = details.purchaseInfo.purchaseData.purchaseState;`
`if (state == PurchaseState.PurchasedSuccessfully)` in `onProductPurchased(String productId, TransactionDetails details)` .

The state is always successful even the order is cancelled in Google Payment Center. Then if I want to consume this already-cancelled order, it'll give me item not owned error (expected).

Thank you.

**Spec**
- which version of library you use
**com.anjlab.android.iab.v3:library:1.0.+**
- was it working in previous versions
 **first time using this library**
- do you use fragments or not
**yes**
- how do you instanciate `BillingProcessor` (singleton or not)
**`bp = new BillingProcessor(this, App.GOOGLE_PLAY_LICENSE_KEY, this);` under `MainActivity.onCreate()`**
- which device/OS version do you use for testing (or its an emulator)
**HTC One (M7), Android 5.0.2
- have you uploaded it to Google Play or not (if yes, when which channel: Prod/Beta/Alpha)
**yes, prod**
- do you test with real products, or with a testing onces (e.g. `android.test.purchased`)
**real managed consumable product**

**Comment by serggl** [comment]
@albionh here is what is known so far: https://github.com/anjlab/android-inapp-billing-v3/issues/44

**Comment by albionh** [comment]
@serggl after testing it again by calling `bp.isPurchased(PRODUCT_ID);` after a period of time that order was cancelled, I actually got it returning `false`. It might just take some time for us to get the updated status.

**Comment by albionh** [comment]
@serggl I discovered that buy calling `bp.isPurchased(PRODUCT_ID);` won't work well if I bought the item on device A and sign in with the same account on devive B, it'll return false. Do you know any way to get it return true?

**Comment by serggl** [comment]
@albionh you can try calling call `loadOwnedPurchasesFromGoogle()` periodically. `bp.isPurchased(PRODUCT_ID)` is using cache, so calling `loadOwnedPurchasesFromGoogle()` is the only way to invalidate this cache

**Comment by HD-AD** [comment]
@serggl Can you please have a look at this issue?

https://github.com/anjlab/android-inapp-billing-v3/issues/318
