### ISSUE TITLE
Subscription IAP Error with  responseCode = 2

### ISSUE THREAD

**Issue by GauravCreed** [anjlab/android-inapp-billing-v3#217]
Hi @serggl 

I am doing little work on it that.

` mBillingProcessor.subscribe(getActivity(), Constants.DMM_MONTHLY_SUBSCRIBE);`

and i getting a first : **Authentication is require , you need to sign into your google account message**, and after that in my logcat error message like **  D/iabv3: resultCode = 0, responseCode = 2**

can u please solve this issue ???
Thanks (_).

**Comment by GauravCreed** [comment]
Hey @serggl 

Any one have a solution for that.....?

**Comment by serggl** [comment]
@GauravCreed dont see any issue from your description. The error message is quite self-descriptive (you need to sign into your google account).
