### ISSUE TITLE
Question: How to get google purchase pop up status? 

### ISSUE THREAD

**Issue by stylianem** [anjlab/android-inapp-billing-v3#218]
To be more specific : I have attached a listener as we can see from the sample project : 
```
   @Override
    public void onClick(View v) {
        String tag = (String)v.getTag();
        
        if(tag.equals(PACKET_1_PRESSED)){
            Log.d("ClickDebug"," 1");

            bp.purchase(getActivity(), SKU_1);
```
The problem comes when the user closes the google play - buy product pop up , then the bp.purchase is being called. Any ideas? 
Thank you

**Comment by serggl** [comment]
there is  some issue outside this code block in your code
