### ISSUE TITLE
Can't check subscription status when apk is signed.

### ISSUE THREAD

**Issue by doldol999** [anjlab/android-inapp-billing-v3#219]
Can't check subscription status when apk is signed.

When I call method bp.isSubscribed(PID) false is always returned.
Tried fetching SKUDetails but keeps getting null.
Take note that all my problems only happens when app is installed using signed apk.

Please give me a feedback about this problem. Or maybe guide me on how to check subscription status (cancelled or not).

Thanks!

**Comment by serggl** [comment]
Please check README, its all in there
