### ISSUE TITLE
FYI: Remove InAppBillingService.aidl before using this library

### ISSUE THREAD

**Issue by ObjectiveTruth** [anjlab/android-inapp-billing-v3#22]
Spent about an hour trying to fix why it wouldn't compile until I found the "Multiple Dex declarations" and after google-Fu, i found the issue was having the aidl file installed. This library already has it.

Was tracking down a bunch of funky errors that didn't make sense...

Thought it might help the next soul with this issue.

Cheers

**Comment by biswajit123** [comment]
Hi, I got some problem while integrating billing library with CreativeSDK(aviary), I got 

> Error:Execution failed for task ':Analyst:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/android/vending/billing/IInAppBillingService$Stub$Proxy.class

this exception. Can you please help me to figure out.

Thanks.

**Comment by raulamoretti** [comment]
I have de same problem with CreativeSDK

**Comment by serggl** [comment]
Can someone else confirm this solution works?

On Tue, Sep 1, 2015 at 6:01 PM Biswajit Ghosh <notifications@github.com>
wrote:

> Hi Guys,
> I solve this problem using extending my Application class to
> MultidexApplication, before it was Class A extends Application, after I
> changed it is Class A extends MultidexApplication.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anjlab/android-inapp-billing-v3/issues/22#issuecomment-136752953>
> .
>
-- 
Sergey, AnjLab

**Comment by rjcristy** [comment]
Not for me @serggl

**Comment by hrskrs** [comment]
If using `MultidexApplication` instead of enabling it from gradle like `multidexEnabled true` i used multidex dependency `compile 'com.android.support:multidex:1.0.1'` and it worked. I didnt use any library for implementing it but i wrote it here in case this will help someone

**Comment by finalhit** [comment]
This is the same issue https://github.com/anjlab/android-inapp-billing-v3/issues/111

**Comment by VishalJogiya** [comment]
Issue Fixed !!!


> You have a duplicate resource entry "IInAppBillingService$Stub$Proxy.class" in your library jar android_6558830429113811056.jar

Just Removed my **aidl** file bcoz 
No need to make any changes in any file just remove your aidl file it worked for me.
Thanks Hope It will help you too.

**Comment by rlee1990** [comment]
I don't have a aidl file to remove
