### ISSUE TITLE
Question: how can I do monthly or yearly subscription using this code?

### ISSUE THREAD

**Issue by harirao001** [anjlab/android-inapp-billing-v3#225]
I want to implement subscription of monthly or yearly.
But I'm ont getting how can I manage using this code

So please help me to achieve this things.

Thanks

**Comment by jagatappv** [comment]
I having same Question.
+1

**Comment by serggl** [comment]
Use `bp.subscribe()`
Here is the guide on how to set up subscriptions: https://developer.android.com/google/play/billing/billing_subscriptions.html

Also sample app from this repo could be useful
