### ISSUE TITLE
loadOwnedPurchasesFromGoogle() function not updating latest details from server

### ISSUE THREAD

**Issue by naveen7r** [anjlab/android-inapp-billing-v3#229]
Hi,

I am testing inapp subscription. I have few questions

My goal is to detect subscription expiration and restrict the user to access content.
Also My app dont have a server. Its an offline app.

In getPurchase call i didnt get expiration details.
Also purchase time not changing when next month billing happened, it still remain same as first billing date.

When i cancel the subscription autoRenewing is changed to false. But from playstore subscription page, my subscription is removed after expiration date occured. But when i query for getPurchase call i am still geting expired product details. But developer docs says only avaliable subscription within the billing periord will come in getPurchase call. 

Please help me to resolve this issue. How to find subscription expried.

**Comment by naveen7r** [comment]
```
Because the Google Play client now caches In-app Billing information locally on the device, you can use the Version 3 API to query for this information more frequently, for example through a getPurchases call. Unlike with previous versions of the API, many Version 3 API calls will be serviced through cache lookups instead of through a network connection to Google Play, which significantly speeds up the API's response time.
https://developer.android.com/google/play/billing/api.html
```

I wish to know when local cache will update. Once i cancel the subscription after the billing periodended, it seems not updating the cache.

Thanks in advance.

**Comment by autonomousapps** [comment]
From discussions elsewhere in the issues here, I think that the cache updates daily, but I'm not aware of any official documentation to that effect.

Closing for now. Please feel free to reopen if there is any action we can take.
