### ISSUE TITLE
Question:  How do i detect autoRenewal of subscription in android app.

### ISSUE THREAD

**Issue by Ravijangra919** [anjlab/android-inapp-billing-v3#231]
i want to update Api on server whenever auto-renewal will happen on google play store. So how can i detect the auto-renewal in android app.

**Comment by serggl** [comment]
In Google updates auto-renewal flag only in case of canceled subscription. If this is what your case is then check for `purchaseInfo.purchaseData.autoRenewing` (as described in a README)

**Comment by Ravijangra919** [comment]
I think you don't understand my point. Suppose a user buy a subscription and at the time of  buy subscription i call a api on server which will register the user's subscription on our server but after one month if renewal is enabled then how i will update the subscription on our server when th.

**Comment by diogojuliano89** [comment]
@Ravijangra919 I'm dealing with the same problem. Did you solve your problem?

**Comment by Ravijangra919** [comment]
@diogojuliano89 i resolved it. We can handle auto renewal at the server end. please read below links for implement it.
https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get
https://developers.google.com/android-publisher/authorization
