### ISSUE TITLE
How to upgrade/downgrade subscriptions?

### ISSUE THREAD

**Issue by gencaysahinn** [anjlab/android-inapp-billing-v3#234]
Firstly thanks for this library. I'm trying to upgrade/downgrade subscriptios.  Google says : 
> 
 
> With version 3 of the In-app Billing API, users can upgrade or downgrade a subscription during its active period.

But how can we do that with this library?

**Comment by serggl** [comment]
@gencaysahinn I guess you're interested in these methods https://github.com/anjlab/android-inapp-billing-v3/blob/master/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java#L329-L366

**Comment by gencaysahinn** [comment]
Yes I was looking that. Thanks @serggl .

**Comment by debasishmondal91** [comment]
@serggl @gencaysahinn can you please help me with the subscription upgrade/downgrade. How can I do that?
