### ISSUE TITLE
Upgrade to using getBuyIntentExtraParams() 

### ISSUE THREAD

**Issue by danielto** [anjlab/android-inapp-billing-v3#241]
Hi, 
I am trying to implement upgrading/downgrading subscriptions. It seems like you already have a method to update subscriptions `updateSubscription()`. In your implementation, you are passing it through the method chain and eventually call `billingService.getBuyIntentToReplaceSkus()`. 

In version 6 of in-app Billing, they recommend to use `billingSerice.getBuyIntentExtraParams()` because it provides some additional functionality. https://developer.android.com/google/play/billing/billing_reference.html#billing-codes

**Comment by serggl** [comment]
done (with kudos went to @ratm)
