### ISSUE TITLE
isSubscribed() always return false

### ISSUE THREAD

**Issue by J0R1SK** [anjlab/android-inapp-billing-v3#243]
Hello, 

I have to display a button if a user is subscribed, but isSubscribed seems to return false even if a user is subscribed. This is the first time I have this problem, because all the tests work on real devices (like Nexus 6 with Android 7 and Nexus 7 with Android 6.0.1), but the problem seems to appear on Samsung Galaxy Tab A (also on Android 6.0.1). I wonder if something differ on these Samsung devices, or if I am missing something... This is the code I am using to check if a subscription:
`billingProcessor.isSubscribed(my_subscription_code)`

P.S. : the following method is working well to check if products are bought:
`billingProcessor.isPurchased(my_product_code)`

Here is what I am using:
`compileSdkVersion 25`
`buildToolsVersion '25.0.0'`
`com.anjlab.android.iab.v3:library:1.0.+`

Thank you by advance for your help.

**Comment by AroundPixels** [comment]
Hi,

Did you check that your are using a device with GooglePlay Services and logged with the same gmail account that you used the purchase test?
I'm getting isSubscribed = true with the last version of the library.

Thanks
