### ISSUE TITLE
Question: How to check if the product is purchased using product id?

### ISSUE THREAD

**Issue by kevalpatel2106** [anjlab/android-inapp-billing-v3#244]
Hi,

I want to know the exact flow of how can I get the list of products already purchased using this library?

Please share me some code for that or the steps.

Here is the code, I am using currently.
       
       boolean listReceived = mBillingProcessor.loadOwnedPurchasesFromGoogle();
        if (listReceived) {
            boolean isPurchased = mBillingProcessor.isPurchased(getString(R.string.pro_product_id));

            Log.d("is purchased", isPurchased + "");
        }

**Comment by binsolb** [comment]
Hi kevalpatel 

I share my code
In my case
`                
    BillingProcessor bp;
    ...
    if (bp.loadOwnedPurchasesFromGoogle() && bp.isPurchased(productId)) {
         //to do something
    }
`
Actually some as you almost.
But If you got BILLING_RESPONSE_RESULT_ITEM_ALREADY_OWNED error
The upper code is useless. the isPurchsed method can't catch history of error's purchase.
If you know something. let me know plz. 
Thanks in advance.

**Comment by kevalpatel2106** [comment]
@binsolb Thank you for sharing the code. Closing the issue.
