### ISSUE TITLE
Why does this library prepend 'subs:<productId>:' to the developer payload?

### ISSUE THREAD

**Issue by autonomousapps** [anjlab/android-inapp-billing-v3#247]
Version: 1.0.38

I'm not sure if this is a feature request or a request to remove an unexpected 'feature' of the lib.

Current behavior: in `BillingProcessor::purchase(Activity, List<String>, String, String, String)` method, there is this block near the top:

```java
String purchasePayload = purchaseType + ":" + productId;
if (!purchaseType.equals(Constants.PRODUCT_TYPE_SUBSCRIPTION)) {
    purchasePayload += ":" + UUID.randomUUID().toString();
}
if (developerPayload != null) {
    purchasePayload += ":" + developerPayload;
}
```

I _did not expect_ this lib to just decide to prepend a string onto my payload. I'm currently porting from a legacy IAB solution to this library (which is very nice, btw!), but this is a blocker. Our backend has particular requirements for the developer payload and this just blows it up.

I'd be happy to file a PR to address this for us, but I'd like to know what you consider to be a good solution. As far as I'm concerned, I'd just remove that second if-statement, since I neither want nor need it. However, I recognize that other users of this lib might already rely on it. Maybe an overloaded `subscribe()` method that doesn't alter the payload?

**Comment by serggl** [comment]
The goal was to easily distinguish managed products / subscription inside a purchased callback (see `handleActivityResult` method source code). Not sure if this is used only in library internals or some users rely on that also (but I would doubt)
If you find a better solution @autonomousapps - PRs are always welcomed

**Comment by autonomousapps** [comment]
I found that other usage after I filed this issue. Is `handleActivityResult` the only place that uses that extra information?

I'll see what I can do in a PR. Thanks!

**Comment by autonomousapps** [comment]
We've actually decided to just adjust our payload verification on the backend to ignore the `subs:<productId>:` code you use, so I'm going to close this issue.

**Comment by autonomousapps** [comment]
@serggl so, we are now going to be relying on the fact that payloads sent with this lib have that string prepended. Given that it's currently an undocumented implementation detail, this means it could change at any time without breaking your public contract. I propose to _document_ this fact and make it part of the public API. If you agree, I'll open a new PR with only some documentation changes.

**Comment by serggl** [comment]
@autonomousapps agree. go ahead

**Comment by autonomousapps** [comment]
https://github.com/anjlab/android-inapp-billing-v3/pull/255
