### ISSUE TITLE
Question: How to handle the scenario in which onProductPurchased() is never called.

### ISSUE THREAD

**Issue by Crymzix** [anjlab/android-inapp-billing-v3#267]
Currently, the library works great with purchasing in-app products in the ideal scenario. But what if a user is purchasing an item (after calling the purchase() method) and the app closes or there is some indiscriminate error preventing the app from ever calling onProductPurchased()? How would I go about recovering from such an error as I do depend on the `purchaseToken` (returned from the TransactionDetails) to verify the purchase on the server side in order to issue any virtual good to the user?

**Comment by autonomousapps** [comment]
You're look for the following methods:

```
billingProcessor.loadOwnedPurchasesFromGoogle()
billingProcessor.listOwnedSubscriptions()
billingProcessor.getSubscriptionTransactionDetails(productId)
```

The first loads all purchases the Google user owns. The second returns a list of owned product IDs. The third will return the TransactionDetails object for the given product ID.
