### ISSUE TITLE
Question: Is it possible to get the number of purchasing specific item by all users from the whole time?

### ISSUE THREAD

**Issue by KonradSzewczuk** [anjlab/android-inapp-billing-v3#268]
I want to have a feature in my app to show user how many times a specific product was bought from the beginning, by anyone. Is it possible to do this with this library or in any kind of solution?

**Comment by AllanWang** [comment]
Late reply, but you can easily log this using a shared preference and incrementing an integer with each successful purchase. However, you can see that this can be abused or lost when uninstalls, something that this library likely can't handle either.

Another way that I track purchases is with [fabric purchase events](https://docs.fabric.io/android/answers/answers-events.html#purchase), which is a lot more robust and persistent. Have a look at that if you are willing to setup a fabric account
