### ISSUE TITLE
TransactionDetails with product id always null on just installed app(after restart and further launching app everything is OK)

### ISSUE THREAD

**Issue by oksett** [anjlab/android-inapp-billing-v3#269]
I have a problem in my app, in which i have to show some bought products in my splash screen.
Problem is, everytime i install new app there are no information about bought products(transactionDetails with specific bought product id is always null), but after launching it again and further launching everything is ok. 
So how can i be up to date, when install app? Is it sort of race condition problem or something?

In my splash screen i just do something like this in my onCreate method:
      
     bp = new BillingProcessor(this, LICENSE_KEY, this);
     TransactionDetails bronzemedal = bp.getPurchaseTransactionDetails("com.example.app.myproductid");
       //this is always null on first installed app version, after further launching it gets it normally
        }

**Comment by autonomousapps** [comment]
It's almost certainly a race condition. You need to wait for the `onBillingInitialized()` hook to be called before trying to interact with the billing processor.

**Comment by oksett** [comment]
Thanks, it worked well!
