### ISSUE TITLE
getPurchaseHistory

### ISSUE THREAD

**Issue by 2math** [anjlab/android-inapp-billing-v3#270]
Hi,
Do you plan to implement **getPurchaseHistory** ?
I see it is in the aidl file of Google's sample [https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive/app/src/main/aidl/com/android/vending/billing/IInAppBillingService.aidl](url)
Thanks in advance and keep the good work!

**Comment by matpag** [comment]
Maybe this method is not [active yet](https://github.com/googlesamples/android-play-billing/issues/53)

**Comment by netomarin** [comment]
@2math and @matpag 
The method is already available on AIDL interface and it's already working.

I've already close this issue in our project.
Thanks.

**Comment by 2math** [comment]
Hi @netomarin ,
My comment was more request than an issue.
And this is what I meant  that is available and working, but not available in this library.

[https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive/app/src/main/aidl/com/android/vending/billing/IInAppBillingService.aidl](url)

[https://github.com/anjlab/android-inapp-billing-v3/blob/master/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java](url)

**Comment by serggl** [comment]
@2math that is definitely a good feature to have, but Im not curtain on the timelime. Would you mine taking a initiative and making a PR?

**Comment by 2math** [comment]
Hi @serggl ,
I'm currently working over 3 projects and 'm pretty busy as well.
But if I there is a delay in btw I will jump on this if no one is and will be glad to contribute.

**Comment by serggl** [comment]
@2math don't tell me 😉

**Comment by syndarin** [comment]
Ready for review https://github.com/anjlab/android-inapp-billing-v3/pull/414

**Comment by syndarin** [comment]
@serggl I suppose this issue could be resolved now.
