### ISSUE TITLE
Multiple dex files define Lcom/android/vending/billing/IInAppBillingService

### ISSUE THREAD

**Issue by zszen** [anjlab/android-inapp-billing-v3#275]
Do you want to request a **feature** or report a **bug**?
bug

What is the current behavior?
eclipse can't build : "[2017-06-05 01:47:06 - Dex Loader] Unable to execute dex: Multiple dex files define Lcom/android/vending/billing/IInAppBillingService;
[2017-06-05 01:47:06 - PandaBubble] Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Lcom/android/vending/billing/IInAppBillingService;
"
Because I use the "google-play-services_lib.jar" for admob, but it contain the IInAppBillingService and "anjlab-iabv3-1.0.40.jar" also contain it.

**Comment by serggl** [comment]
duplicates #111
