### ISSUE TITLE
Transaction was declined....problem

### ISSUE THREAD

**Issue by zszen** [anjlab/android-inapp-billing-v3#277]
Do you want to request a **feature** or report a **bug**?
bug

What is the current behavior?
I typed the iab code with anjlab. And I can't get success with it.

I don't know why about it. It occur with original api and anjlab api together. I have cost my money with Play Market app iab ( other developer ) successful. But I can't get success with my own beta app. 

![screenshot](https://cloud.githubusercontent.com/assets/1890538/26783496/190c5bf8-4a2b-11e7-8fea-c1dcb1d32557.jpg)

**Comment by serggl** [comment]
To few details to help you. Please provide more info what exactly doesn’t work

**Comment by zszen** [comment]
I get the supported eclipse "google-play-service-lib" from here:
https://github.com/xulingchung2016/google-play-services_lib

I don't known what it is error. Or the code out of date.
