### ISSUE TITLE
Question: how do I purchase iap with different google account?

### ISSUE THREAD

**Issue by dreasn** [anjlab/android-inapp-billing-v3#284]
How do I purchase iap with different google account?
I've tried to change the account in PlayStore but in my app it still refer to first account.

Do you want to request a **feature** or report a **bug**?
feature

What is the current behavior?
User can't do iap with other google account.

- which version of library you use?  The latest.
- was it working in previous versions? First time
- do you use fragments or not? No.
- how do you instanciate `BillingProcessor` (singleton or not)? singleton/
- real device. Android Marshmallow
- I have uploaded to alpha.  Setup tester account done.
- tested with real product.

**Comment by AllanWang** [comment]
I'm not sure if this is an issue on the library's end. One way of switching accounts is to uninstall the app, go on desktop, and press the install button from the proper account there. As you've noticed changing accounts in the app doesn't always solve it

**Comment by autonomousapps** [comment]
You need to have multiple accounts on your device.
