### ISSUE TITLE
Question: joda-time remove

### ISSUE THREAD

**Issue by sergey-pokrovskyi** [anjlab/android-inapp-billing-v3#285]
since you'v added
`joda-time:joda-time:2.9.9`

i'm using this android wrapper of joda-time - https://github.com/dlew/joda-time-android

but, joda-time-android is incompatible with using the base joda-time library.

So, the question is:
would you consider remove original joda-time library?
or if not
Is it safe to remove joda-time and rebuild the library?
Because of:
http://blog.danlew.net/2013/08/20/joda_time_s_memory_issue_in_android/

**Comment by serggl** [comment]
removed in 1.0.42
