### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by varotariyavm** [anjlab/android-inapp-billing-v3#288]
I am getting error "java.lang.NoSuchMethodError: com.android.vending.billing.IInAppBillingService.getBuyIntentToReplaceSkus" while using method for update subscription as "billingProcessor.updateSubscription(Activity,OldProductId, NewProductId);"

**Comment by serggl** [comment]
you must check for this API availability via `isSubscriptionUpdateSupported()`  before calling `billingProcessor.updateSubscription`

**Comment by varotariyavm** [comment]
Yes i check isSubscriptionUpdateSupported() before calling billingProcessor.updateSubscription, but getting same issue.

**Comment by serggl** [comment]
which version of library are you using? have you ever modified bundled `AIDL` file by hand? My guess is that you did, or at least some other library that you use does

**Comment by varotariyavm** [comment]
I am using one library "com.aviary.android.feather.sdk:aviary-sdk:3.6.6" which is contain iinappbilling serivce, but i exclude that using "exclude group: 'com.android.vending.billing,com.aviary.android.feather.cds.billing.util'" and for my iinapppurchase i am using "anjlab-iabv3-current.jar" file.

**Comment by varotariyavm** [comment]
Hello @Sergey you are right, finally i found issue, after fully remove aviary library everything is working fine...but when i use aviary library getting this issue, if you have any idea please let me know...and thank you for your kind support.

**Comment by serggl** [comment]
based on my own experience with aviary library (#111) I had to re-package their lib to remove AIDL file completely. But I can't say that this is the best way to go

**Comment by varotariyavm** [comment]
I want to remove IInAppBillingService from aviary library, is there any way to do it. I tried to using exclude but its not help me more.

**Comment by serggl** [comment]
I was fixing this by something like this one: https://stackoverflow.com/questions/38860912/modifying-contents-of-android-aar-file-converting-to-and-from-zip-format

**Comment by varotariyavm** [comment]
ok @serggl , Thanks for reply i will check and inform here.

**Comment by varotariyavm** [comment]
Finally issue solved, First of all I get jar file from "app/build/intermediates/exploded-aar/com.aviary.android.feather.sdk/cds-library/3.2.8/jars" extract it and then delete files which are contain IInAppBillingService classes and and put this jar in libs folder and add as external dependency  in project and exclude this library from aviary like as below,
`compile('com.aviary.android.feather.sdk:aviary-sdk:3.6.6') {
exclude module: 'cds-library'
}`

Thank you so much @serggl for helping and giving your valuable time...!!!
