### ISSUE TITLE
errorCode 101

### ISSUE THREAD

**Issue by abozanona** [anjlab/android-inapp-billing-v3#292]
When I run the code i get `int errorCode` = 101 and Throwable `error` = null 

I added the permission `com.android.vending.BILLING` and in the dependency `com.anjlab.android.iab.v3:library:1.0.43`
    
Here's my code

    public class BuyPointsActivity extends AppCompatActivity implements BillingProcessor.IBillingHandler {

        Button btnBuyPoints;
        EditText txtPoints;

        BillingProcessor bp;

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_buy_points);

            //bp = new BillingProcessor(this, "YOUR LICENSE KEY FROM GOOGLE PLAY CONSOLE HERE", this);
            bp = new BillingProcessor(this, null, this);
            bp.initialize();

            btnBuyPoints=(Button) findViewById(R.id.btnBuyPoints);
            txtPoints=(EditText) findViewById(R.id.txtPoints);

            btnBuyPoints.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    //bp.purchase(BuyPointsActivity.this, "YOUR PRODUCT ID FROM GOOGLE PLAY CONSOLE HERE", "DEVELOPER PAYLOAD HERE");
                    bp.purchase(BuyPointsActivity.this, "android.test.purchased");
                    //bp.subscribe(BuyPointsActivity.this, "YOUR SUBSCRIPTION ID FROM GOOGLE PLAY CONSOLE HERE", "DEVELOPER PAYLOAD HERE");
                }
            });

        }

        @Override
        public void onProductPurchased(String productId, TransactionDetails details) {
            Toast.makeText(this, "1000 point was succ. add to your account", Toast.LENGTH_LONG).show();
        }

        @Override
        public void onPurchaseHistoryRestored() {

        }

        @Override
        public void onBillingError(int errorCode, Throwable error) {
            Toast.makeText(this, "error while purchasing points. " + errorCode, Toast.LENGTH_LONG).show();
        }

        @Override
        public void onBillingInitialized() {

        }

        @Override
        protected void onActivityResult(int requestCode, int resultCode, Intent data) {
            if (!bp.handleActivityResult(requestCode, resultCode, data)) {
                super.onActivityResult(requestCode, resultCode, data);
            }
        }

        @Override
        public void onDestroy() {
            if (bp != null) {
                bp.release();
            }
            super.onDestroy();
        }
    }

**Comment by abozanona** [comment]
The problem was because my country is not supported in Play. I tried to install VPN and change my country and the same code is now working like a charm.

**Comment by kriti-1** [comment]
How exactly you solved your problem? Even i am having 101 error

**Comment by abozanona** [comment]
What is your country? What is your mobile device type? Did you try your application on a modern mobile device?

**Comment by kriti-1** [comment]
i am from india. and i am trying it on 6.0 version.
