### ISSUE TITLE
loadOwnedPurchasesFromGoogle() always returns false

### ISSUE THREAD

**Issue by edcastrahul** [anjlab/android-inapp-billing-v3#298]
loadOwnedPurchasesFromGoogle() always returns false.Any Help?

**Comment by serggl** [comment]
this means BillingProcessor is either not initialised or there was some error posted to the Logcat

**Comment by edcastrahul** [comment]
thanks. issue solved

**Comment by BaraiyaHaresh007** [comment]
how to handle cancel subscription to play store account in my app to check its active or not

**Comment by Rehmat-un-Nisa** [comment]
can you share the solution
