### ISSUE TITLE
Question: Why does the service not bind?

### ISSUE THREAD

**Issue by nscherer** [anjlab/android-inapp-billing-v3#301]
I'm trying to check for and consume purchases on app startup.  In my startup activity:
```

@Override
    protected void onCreate(Bundle savedInstanceState) {
//...
billingProcessor = BillingProcessor.newBillingProcessor(this,
                "MY_KEY",
                this);

        billingProcessor.initialize();
//...
}

    @Override
    public void onProductPurchased(@NonNull String productId, @Nullable TransactionDetails details) {

    }

    @Override
    public void onPurchaseHistoryRestored() {
        List<String> skus = billingProcessor.listOwnedProducts();
        for(String sku : skus){
            if(billingProcessor.consumePurchase(sku)){
                // TODO take appropriate action
                logger.debug("Consumed " + sku);
            } // else error will be reported
        }

        // TODO need to figure out when this process is complete, or do it in the Application
    }

    @Override
    public void onBillingError(int errorCode, @Nullable Throwable error) {
        logger.severe("Billing error " + errorCode,error);
    }

    @Override
    public void onBillingInitialized() {

        logger.debug("Billing initialized");
    }
```

Neither onBillingInitialized nor onBillingError is ever called.  When I step into the library code, it calls this:

```
getContext().bindService(getBindServiceIntent(), serviceConnection, Context.BIND_AUTO_CREATE);
```

but the methods on the ServiceConnection are never called.  There are no errors in logcat.  I'm using version 1.0.44 of your library testing on a Galaxy S6 running Lollipop, and my app is uploaded to the alpha channel in the Play store.

**Comment by ankitbatra11** [comment]
I am facing a similar issue on a device which does not have Google Play Store installed. However, I would imagine library to handle this and provide a billing error callback.

**Comment by autonomousapps** [comment]
It seems likely your test device doesn't have Google Play Services installed, as suggested by @ankitbatra11 . In fact, this library _does_ help with determining availability of GPS. You must call the method `boolean isAvailable = BillingProcessor.isIabServiceAvailable();`, as noted in the readme.
