### ISSUE TITLE
onProductPurchased is not getting called after successful purchase .

### ISSUE THREAD

**Issue by mianaliasjad** [anjlab/android-inapp-billing-v3#304]
i purchase a item and it was successfully purchased but after successful purchase onProductPurchased was not called .

**Comment by mianaliasjad** [comment]
IF any one face the problem that in fragment after purchasing onProductPurchased method does not get called then override OnActivityResult of your Activity not of fragment you will get the result there also :)

**Comment by HD-AD** [comment]
I did Override OnActivityResult and I still get onBillingError after the purchase has been made successfully? onProductPurchased is only called after the purchase is made successfully and I try to purchase again?

**Comment by jatin-lakhani** [comment]
+1
onProductPurchased is only called after the purchase is made successfully and I try to purchase again..

First time callback not coming and 2nd and subsequent time callback is coming.
Why the callback is not coming at the first time of purchase only?
