### ISSUE TITLE
How to check subcription validity

### ISSUE THREAD

**Issue by dineshoffl** [anjlab/android-inapp-billing-v3#306]
hi
thanks for this lib

i want to know how to check validity of subscription at launch of app then let the user enter the app if
Subcription Expired user should be blocked from using my app.
thanks

**Comment by TikTak123** [comment]
@dineshoffl Hi
I have the same problem did you find the answer to this question?

**Comment by autonomousapps** [comment]
https://github.com/anjlab/android-inapp-billing-v3/issues/348
