### ISSUE TITLE
Question: how do I check subscription expired

### ISSUE THREAD

**Issue by hoanghiephui** [anjlab/android-inapp-billing-v3#316]
Hi team dev

I'm beginning to explore this library. Please give me instructions on how to check for subscription expired

Thanks!

**Comment by meddd** [comment]
You heave to use https://developers.google.com/android-publisher/api-ref/purchases/subscriptions

**Comment by TikTak123** [comment]
Hi @hoanghiephui 
I have the same problem did you find the answer to this question?

**Comment by autonomousapps** [comment]
https://github.com/anjlab/android-inapp-billing-v3/issues/348
