### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by rk8339811** [anjlab/android-inapp-billing-v3#322]
I want to report a Bug.

```
bp.isOneTimePurchaseSupported();` Gives me the following error.

```
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'int com.a.a.a.a.a(int, java.lang.String, java.lang.String)' on a null object reference
```

bp is the `BillingProcessor` variable.

I am checking if bp is not null & has been initialized.

This is how I am doing it.

```
if(bp!=null&&is_bp_ini == true)
{
    boolean isOneTimePurchaseSupported = bp.isOneTimePurchaseSupported();` 
    if(isOneTimePurchaseSupported )
    {
      // Do Something
    }
}
```
```is_bp_ini``` is a Boolean value which by default is set to false but on the `onBillingInitialized `I am setting it to true.

This is how I am doing It

```
@Override
    public void onBillingInitialized() {
        is_bp_ini = true;
        bp.loadOwnedPurchasesFromGoogle();
    }
 ```

This is how I am initializing the bp

```
 bp = BillingProcessor.newBillingProcessor(this, "ID");
        bp.initialize(); 
```
I am not able to reproduce the error but this error has occurs on more than 8 Devices running on Android 5,6 and 7 from different manufactures like Samsung/Oppo/HTC etc. 

My app has already been uploaded to the Play Store.

I am importing the library using  `compile 'com.anjlab.android.iab.v3:library:1.0.+'`

**Comment by tommyzat** [comment]
+1

**Comment by autonomousapps** [comment]
I would suggest dropping your custom `is_bp_ini` and instead use the instance method on the class. See how it's defined:
```
    public boolean isInitialized() {
        return this.billingService != null;
    }
```
If that returns true, then the service is non-null and your subsequent call to `isOneTimePurchaseSupported()` should not encounter an NPE.*

*not quite true, as the system is asynchronous by nature and there is an inherent race condition that could lead to the billing service being set to null in between `isInitialized()` and `isOneTimePurchaseSupported()`.

The billing service is set to null if the service connection is disconnected. This could happen at any time.

Probably the best you can do is wrap in a try/catch and then try to re-init the billing processor if this happens. In my own app, I have error-handling like this. I will show a Snackbar to my users and invite them to retry, which re-initializes the whole system. Under certain circumstances, the app will also retry silently.

**Comment by rk8339811** [comment]
@autonomousapps Really Sorry for the late reply. Actually I am also checking if the billing service is null or not. At the same time I am also verifying whether it is initialized and only after billing service is not null and it has been initialized I am calling` isOneTimePurchaseSupported(). ` Your `try{}catch{} `method seems interesting and I will surely use that method to avoid these kind of conditions. Thanks for your response.
