### ISSUE TITLE
Question: How do I use a fakeVisa to know if what comes before pay it's ok or not

### ISSUE THREAD

**Issue by joancolmenerodev** [anjlab/android-inapp-billing-v3#324]
My question is quite easy, I'm wondering how do I use the fake Visa to make the onProductPurchased() be fired, so I can do more stuff with that.

I'm actually using:
 new BillingProcessor(this, getResources().getString(R.string.google_play_license_key),HERE****, new BillingProcessor.IBillingHandler()

where I put HERE**** I'm using the customer_id from google play because I thought with this I could use the fakeVisa but not... I'm usually use this without that customer_id.

Any idea how to make like a tester pay?

**Comment by jamez14** [comment]
[The Google Play Billing documentation](https://developer.android.com/google/play/billing/billing_testing.html) has some good info on how to do test payments
