### ISSUE TITLE
BillingProcessor.isSubscribed() always returning true, loadOwnedPurchasesFromGoogle() don't help

### ISSUE THREAD

**Issue by zohaibshamshad** [anjlab/android-inapp-billing-v3#335]
Please fix this issue.
BillingProcessor.isSubscribed is always true, even after the subscription is expired and autoRenew is false

**Comment by andrewpmoore** [comment]
I'm seeing exactly the same thing at the moment that I've just been debugging in my app

**Comment by zohaibshamshad** [comment]
I came up with the alternate.
I am getting purchase time`transactionDetails = BillingProcessor.getSubscriptionTransactionDetails(productId);` 
then`PURCHASE_TIME_IN_MILI = transactionDetails.purchaseInfo.purchaseData.purchaseTime.getTime();
            EXPECTED_TIME_FOR_SUBSCRIPTION_TO_EXPIRE = PURCHASE_TIME_IN_MILI + ONE_MONTH_IN_MILI; // if it is one month subsription
            CURRENT_TIME_IN_MILI = //get the current time here

            if(EXPECTED_TIME_FOR_SUBSCRIPTION_TO_EXPIRE > CURRENT_TIME_IN_MILI){
                subscriptionStatus = true;
                Log.i("one month Subscription", "True");
            }`
This may help you

**Comment by Andy671** [comment]
The same. Has anyone found a solution?

**Comment by knife-s** [comment]
same here.

**Comment by fastian481** [comment]
yes bp.isSubscribed always returning true. This lib will not be useful if this issue persists.

Kindly resolve this issue.

**Comment by walkmn** [comment]
I have the same. Please fix.

**Comment by antranvn** [comment]
Can you check by this following snippet:

bp.getSubscriptionTransactionDetails("subscribe_id").purchaseInfo.purchaseData.autoRenewing;

**Comment by autonomousapps** [comment]
PRs welcome!

**Comment by AroundPixels** [comment]
Same problem here, return is always true even if the subscription is cancelled.
Library update will be a present for us :)

**Comment by KKKoTTT** [comment]
Anybody know workaround?

**Comment by AroundPixels** [comment]
As @antranvn said, you can check autoRenewing to know if the subscription is cancelled (will return false), but you must check the date to maintain subscription until end date.

Hope anjlab can update and fix the isSubscribed method.

**Comment by autonomousapps** [comment]
it might be because I'm using an older version of the library, but I've noticed that `autoRenewing=true` even after a user has cancelled. I need to dig more into that.

**Comment by KKKoTTT** [comment]
I don't get how to calculate end date to maintain subscription after it's cancelled as PurchaseData.purchaseTime returns date of the first purchase, not the last renew date.

**Comment by KKKoTTT** [comment]
Nevermind, it seems that this is not a library issue, this is how google api works. Cancelled expired subscriptions become inactive in 1-2 days anyway (after google play cache cleared - com.android.vending).

**Comment by knife-s** [comment]
I solved my problem. The problem was that someone made a mistake with the sku. It was a purchase sku and it must be a subscription sku.

The problem disappeared after we created the correct sku type.

hope this helps someone else. <3

**Comment by goraga1** [comment]
For example , I test app with beta 10/minute sub , but after 10 minutes its not update, because this part 
return turn , but after re-installing app it works. 

`    public boolean isUserSubscribed() {
        User user = UserHelper.getInstance().getUser(getApplicationContext());

        if (user != null)
            if (bp.loadOwnedPurchasesFromGoogle() && bp.isSubscribed(user.getSubId())) {
                return true;
            }
        return false;
    }`

**Comment by ImDroidGuy** [comment]
Hey Guys ! I also faced this issue, i thought it was due to library error like you guys, but the fact is usually google take 2-3 days for updating the subscription in our app. You can check this by changing the "Date and Time(i.e one or two days from current date ) " settings in your Mobile Phone. Then try to restart the App. if doesnt work try to clear the App Cache and repeat the the same thing ...

**Comment by autonomousapps** [comment]
Closing this in favor of https://github.com/anjlab/android-inapp-billing-v3/issues/348

**Comment by nikitoSha** [comment]
> bp.getSubscriptionTransactionDetails("subscribe_id").purchaseInfo.purchaseData.autoRenewing

Not working :( Always true. Even if user unsubscribed.
