### ISSUE TITLE
isSubscribed not working correctly

### ISSUE THREAD

**Issue by chaser79** [anjlab/android-inapp-billing-v3#343]
Hello all,

Im trying to implement subscriptions in my app using this library.

the isSubscribed(SubscriptionID) method doesn't seem to work correctly.

It is returning false before the subscription is brought then returns true on successful purchase. The problem is when the subscription gets cancelled and ends isSubscribed() is still returning true. 

I am calling loadOwnedPurchasesFromGoogle() to refresh the subscription but it seems that the cache never gets cleared and new data requested from google. I think the problem is loadOwnedPurchasesFromGoogle() as it doesn't seem to be clearing the cache.

I have tried used getSubscriptionTransactionDetails(...) and checking the autoRenewing flag which works but returns false after a subscription has been cancelled but hasn't expired. This could work if i could get the expiry date of the subscription to check if it has truly expired.

 Has anyone found an answer to solve this or implemented there own subscription check?

Thanks for the help.

**Comment by chaser79** [comment]
After looking into it more loadOwnedPurchasesFromGoogle() does seem to clearing and re entering the cache as the autoRenewing flag of a subscription changes instantly when a subscription is cancelled. Could the problem be that subscriptions are still being returned when refreshing the cache even though they have expired? Is this a problem with google its self or a problem with googles sandbox in app billing.
Im new to use google in app billing so trying to get my head around it now.

**Comment by chaser79** [comment]
Okat more information. If you clear the data off the google play store app on the phone the isSubscribed() returns false again. I guess this is just how it works as its getting the data from google play app and you can't force that app to clear its cache. Anyone know how often the google play app clears its cache?

**Comment by chaser79** [comment]
I have done some testing on this and it seems that google play app clears its cache around every 24hours. So the user can get up to 24 hours free subscription depending on what time they subscribed. Not sure if you could force google play app to clear its cache from your own app. The only other way I can see it what other people have said where you verify the subscription through a back end using googles api's. This way is good but can be a problem if your not creating any user accounts to tie the subscription data too. Im using it to unlock event programmes so for me its not the end of the world of the user un subscribed and get a few hours for free.

**Comment by Arrenign** [comment]
Yeah lol I too use it only to provide a shared preference to give the user the option to disable any ads..so not a big deal loosing a few cpm or cpc for a few hours. To my knowledge I cant find a way to clear the cache though. I mean to really think they would give you that option to access a phones cache is scary and they would like be "hell nah" we ain't gonna be the next zuck at the senate meeting lol

**Comment by ImDroidGuy** [comment]
Hey Guys ! I also faced this issue, i thought it was due to library error like you guys, but the fact is usually google take 2-3 days for updating the subscription in our app. You can check this by changing the "Date and Time(i.e one or two days from current date ) " settings in your Mobile Phone. Then try to restart the App. if doesnt work try to clear the App Cache and repeat the the same thing ...

**Comment by chaser79** [comment]
Yeh they might work but I'm not willing to try it either. Just let google play clear is own cache. It's odd tho that the google play app doesn't update its cache when a subscription ends. Google play app updates is subscription list. If it then update its cache at the same time we wouldn't be having this problem. Hopefully they will update it so it updates is cache when subscription's change.

**Comment by autonomousapps** [comment]
Hey guys, I'm going to close this issue in favor of this one: https://github.com/anjlab/android-inapp-billing-v3/issues/348

At the very least, it seems we need to update our docs to explain this _very common question_ about subscriptions and the Google Play cache. If one of you wants to create a PR that does that (updates our README), we'd be much obliged!
