### ISSUE TITLE
Question: Why does my subscription details not save

### ISSUE THREAD

**Issue by Teksun** [anjlab/android-inapp-billing-v3#346]
Been banging away at this for several weeks. I can subscribe and the app acts as intended. But when I close the app and open it again it is as though I am not subscribed. If I click the subscribe button I get "you already have a sub".  I know there is an easy answer, I just can't figure out what to coed where.

My MainActivity needs to retrieve the isSubscribed boolean from the GetSub Activity:

if (GetSub.isSubscribed) {
            Button grammarButton = findViewById(R.id.grammar_button);
            grammarButton.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Intent i = new Intent(getApplicationContext(), GrammarActivitySub.class);
                    startActivity(i);
                }
            });
        } else {
            Button grammarButton = findViewById(R.id.grammar_button);
            grammarButton.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Intent i = new Intent(getApplicationContext(), GrammarActivity.class);
                    startActivity(i);
                }
            });
        }
---------------------
This is GetSub.class
----------------
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_get_sub);
        bp = new BillingProcessor(this, LICENSE_KEY, this);
        // or bp = BillingProcessor.newBillingProcessor(this, "YOUR LICENSE KEY FROM GOOGLE PLAY CONSOLE HERE", this);
        // bp = new BillingProcessor(this, null, this);

        if(!BillingProcessor.isIabServiceAvailable(this)) {
            showToast("In-app billing service is unavailable, please upgrade Android Market/Play to version >= 3.9.16");
        }

        subscribe = findViewById(R.id.subscribe_button);
        //subscribe.setVisibility(View.INVISIBLE);
        subscribe.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                bp.subscribe(GetSub.this, SUBSCRIPTION_ID);
            }
        });

        restoreSub = findViewById(R.id.button_restore);
        restoreSub.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                bp.loadOwnedPurchasesFromGoogle();
            }
        });

        if (!isSubscribed){
            returnToMain = findViewById(R.id.to_main_activity);
            returnToMain.setVisibility(View.INVISIBLE);
        }

    }

    @Override
    public void onProductPurchased(@NonNull String productId, @Nullable TransactionDetails details) {
        subscribe.setVisibility(View.INVISIBLE);
        isSubscribed = true;

        returnToMain = findViewById(R.id.to_main_activity);
        returnToMain.setVisibility(View.VISIBLE);
        returnToMain.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent i = new Intent(getApplicationContext(), MainActivity.class);
                startActivity(i);
            }
        });

    }

    @Override
    public void onPurchaseHistoryRestored() {
        subscribe.setVisibility(View.INVISIBLE);
        isSubscribed = true;
        returnToMain = findViewById(R.id.to_main_activity);
        returnToMain.setVisibility(View.VISIBLE);
        returnToMain.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent i = new Intent(getApplicationContext(), MainActivity.class);
                startActivity(i);
            }
        });

    }

    @Override
    public void onBillingError(int errorCode, @Nullable Throwable error) {
        bp.loadOwnedPurchasesFromGoogle();
        Toast toast=Toast.makeText(getApplicationContext(),"Something Went Wrong",Toast.LENGTH_SHORT);
        toast.show();
        returnToMain = findViewById(R.id.to_main_activity);
        returnToMain.setVisibility(View.INVISIBLE);
    }

    @Override
    public void onBillingInitialized() {

    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (!bp.handleActivityResult(requestCode, resultCode, data))
            super.onActivityResult(requestCode, resultCode, data);
    }
    private void showToast(String message) {
        Toast.makeText(this, message, Toast.LENGTH_LONG).show();
    }
    public void loadOwned(){
        bp.loadOwnedPurchasesFromGoogle();
    }
    private void removeAds() {
        isSubscribed = true;
    }

    @Override
    public void onDestroy() {
        if (bp != null)
            bp.release();
        super.onDestroy();
    }
}
------------------------

How do I check for that sub. after the app is closed and reopened?
Kind of a nub so any help is appreciated.
It also appears I do not know how to "label this a question"

**Comment by ImDroidGuy** [comment]
Hey Guys ! I also faced this issue, i thought it was due to library error like you guys, but the fact is usually google take 2-3 days for updating the subscription in our app. You can check this by changing the "Date and Time(i.e one or two days from current date ) " settings in your Mobile Phone. Then try to restart the App. if doesnt work try to clear the App Cache and repeat the the same thing ...

**Comment by autonomousapps** [comment]
@Teksun  you need to persist the data somehow. For example, with `SharedPreferences`.
