### ISSUE TITLE
Consume doesn't work?

### ISSUE THREAD

**Issue by cellojaan** [anjlab/android-inapp-billing-v3#358]
- which version of library you use - **1.0.44**
- was it working in previous versions? - **First time I'm using this library.**
- do you use fragments or not - **Not**
- how do you instanciate `BillingProcessor` (singleton or not) - **BillingProcessor bp;**
- which device/OS version do you use for testing (or its an emulator) - **Android 8.0**
- have you uploaded it to Google Play or not (if yes, when which channel: Prod/Beta/Alpha) - **Alpha**
- do you test with real products, or with a testing onces (e.g. `android.test.purchased`) - **Real Products**

Hi to everyone. I want to try this library is also great. But, consumePurschase doesn't work. Nothing happen. All products is working but consume doesn't work. 

I uploaded in Google Play Store in Alpha and I downloaded new alpha update. But still same. I'm calling the consume how is in sample.

When I call TransactionDetails but return null.

` bp.loadOwnedPurchasesFromGoogle();
        TransactionDetails transactionDetails = bp.getSubscriptionTransactionDetails(productId);
        System.out.println(transactionDetails);`

What can I do more?
Thanks.

**Comment by cellojaan** [comment]
I did;

bp.consumePurchase(productId);
bp.purchase(activity,productId);

Solved for me. Thanks.

**Comment by mustii82** [comment]
Please Fix this issue in the codebase!

**Comment by mustii82** [comment]
will this fix consume the purchased product ?

**Comment by cellojaan** [comment]
Yes ofcourse.

First use consume after product purchase. Example:

bp.consumePurchase(skuID);
bp.purchase(YourActivity.this,skuID);

**Comment by mustii82** [comment]
will it consume the product?

**Comment by cellojaan** [comment]
Yes

**Comment by GauravCreed** [comment]
`bp.consumePurchase(skuID);`
`bp.purchase(YourActivity.this,skuID);`


This will consume product from google play ?

**Comment by cellojaan** [comment]
> `bp.consumePurchase(skuID);`
> `bp.purchase(YourActivity.this,skuID);`
> 
> This will consume product from google play ?

Yes. Use like this.

**Comment by harshid** [comment]
@cellojaan 
I am created in app id in managed products for consume products.i used below code
```
bp.consumePurchase(skuID);
bp.purchase(YourActivity.this,skuID);
```
I upload apk in alpha testing but i am getting **"The item you requested is not available for purchase"** message. 

Item already active in playstore.please help me.
