### ISSUE TITLE
How to get purchase toket from this library?

### ISSUE THREAD

**Issue by cellojaan** [anjlab/android-inapp-billing-v3#362]
Hi.

I'm using a lot time this library and I like this. But I want to take purchase token after the purchase. How is possible any body know that?

**Comment by blood73** [comment]
Hi! You can try with this:

`public void onProductPurchased(String productId, TransactionDetails details) {
    details.purchaseInfo.purchaseData.purchaseToken;
}
`

**Comment by cellojaan** [comment]
Thanks @blood73
