### ISSUE TITLE
Code does not reach onProductPurchases or onActivityResult

### ISSUE THREAD

**Issue by krishnakanthpps** [anjlab/android-inapp-billing-v3#382]
Here is the detailed issue which I am facing which I posted in the StackOverflow. 
https://stackoverflow.com/questions/53874409/onproductpurchased-and-onactivityresult-not-called-after-a-successfull-purchase

_What is the current behavior?_ Unable to reach the onProductPurchase or onActivityResult once a purchase is completed. I need to trigger a call once a purchase is successful. 

Don't forget to mention:
- which version of library you use : v3
- was it working in previous versions? N/A
- do you use fragments or not Yes. I do.
- how do you instanciate `BillingProcessor` (singleton or not): Yes. Code in the SO link
- which device/OS version do you use for testing (or its an emulator) : Asus Android 8.1.0, API 27 and API 23
- have you uploaded it to Google Play or not (if yes, when which channel: Prod/Beta/Alpha) : Prod
- do you test with real products, or with a testing onces (e.g. `android.test.purchased`) : Real

This functionality is very critical for my app.

**Comment by SaadBilal** [comment]
Any luck on this?

**Comment by krishnakanthpps** [comment]
I moved to Google Play Billing. I could not find a resolution to this issue. 
https://developer.android.com/google/play/billing/billing_overview
