### ISSUE TITLE
purchaseList always return empty array, not null, so check isPurchased always return true

### ISSUE THREAD

**Issue by VanHop94** [anjlab/android-inapp-billing-v3#385]
sorry my mistake

**Comment by kartikj07** [comment]
@VanHop94 what did you do to solve your issue? I think I am encountering a similar issue

**Comment by VanHop94** [comment]
> @VanHop94 what did you do to solve your issue? I think I am encountering a similar issue

When check isPurchased We need to attach payment id. Example: bp.isPurchased("YOUR IN-APP ID")

**Comment by kartikj07** [comment]
I have tried this but when I switch fragments then I am not getting isPurchased as true. I am getting it false everywhere and on every screen.

**Comment by kartikj07** [comment]
> > @VanHop94 what did you do to solve your issue? I think I am encountering a similar issue
> 
> When check isPurchased We need to attach payment id. Example: bp.isPurchased("YOUR IN-APP ID")

I have tried this but when I switch fragments then I am not getting isPurchased as true. Even after sucessful purchase, I am getting it false everywhere and on every screen.
