### ISSUE TITLE
[supply] Update to Google Play Developer API v3 (v2 end of life Dec 2019)

### ISSUE THREAD

**Issue by judyann63** [anjlab/android-inapp-billing-v3#406]
[Help] need to Update to v3 Api !!

**Comment by mustii82** [comment]
Which Version is currently used ?

**Comment by roboticvn** [comment]
I also received this notification from Google. Hope to have an update soon

**Comment by serggl** [comment]
Volunteers for a PR? ;)

**Comment by tastyone** [comment]
Does this project NOT use v3 API?

**Comment by mustii82** [comment]
#411 is currently working on that Problem

**Comment by DennyWeinberg** [comment]
Any news here? Any information when it will be done? Or do we need to switch to another library?

**Comment by mustii82** [comment]
@DennyWeinberg I ask myself the same question every Month :D

**Comment by jin-conbus** [comment]
@DennyWeinberg 
Do not worry too much.
I manage a lot of projects, and this warning appears to appear in all projects that use the 'billing' library.

For the sake of safety, we have committed to using the latest 'billing' library, so let's wait.

**Comment by judyann63** [comment]
Supply Completed ! :*
