### ISSUE TITLE
L preview : IllegalArgumentException : Service Intent must be explicit: Intent { act=com.android.vending.billing.InAppBillingService.BIND

### ISSUE THREAD

**Issue by eboudrant** [anjlab/android-inapp-billing-v3#41]
Here the error in the logs :

```
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.android.vending.billing.InAppBillingService.BIND }
```

With the L preview released on 17th October

**Comment by Voyz** [comment]
This problem is still happening on Android 6.0.1. Changing initialisation from:

    this.getContext().bindService(new Intent("com.android.vending.billing.InAppBillingService.BIND"), this.serviceConnection, 1);

to:

    Intent intent = new Intent("com.android.vending.billing.InAppBillingService.BIND");
    intent.setPackage("com.android.vending");
    this.getContext().bindService(intent, this.serviceConnection, 1);

Seems to fix the problem

**Comment by serggl** [comment]
@Voyz that should be fixed for a while. Try out  v1.0.38

**Comment by Voyz** [comment]
Sorry, take that back, somehow this:

`compile 'com.anjlab.android.iab.v3:library:1.0.+'`

resolved to:

`compile 'com.anjlab.android.iab.v3:library:1.0.9'`

and pulled an old version of the library. After changing to 1.0.38 everything works fine.
