### ISSUE TITLE
Cancel subscription 

### ISSUE THREAD

**Issue by pranavlathigara** [anjlab/android-inapp-billing-v3#412]
i am wonder that is there any method for cancel subscription ?

**Comment by Duna** [comment]
Did you find a solution, i am facing the same issue

**Comment by pranavlathigara** [comment]
No we can not cancel subscription direct from the app, we can only
cancel subscription from play store

**Comment by Duna** [comment]
@pranavlathigara is this in-app billing google limilitation?

**Comment by pranavlathigara** [comment]
yes might be ,  as of now i did not get any option for canceling subscription
