### ISSUE TITLE
warning in google play to use V3 developer api

### ISSUE THREAD

**Issue by shravanvinu** [anjlab/android-inapp-billing-v3#423]
hi m using  
com.anjlab.android.iab.v3:library:1.0.44'
since January. 
its working fine.. but today i saw a notice in google play saying your are using version 1 or version 2 of developer api.. update to version 3. old version will not work after December 2019
 m i using any old version of anjlab library?
 i can see the 'com.android.billingclient:billing:2.0.1' is used in this version .. need any updates?
or if anything major changed in com.anjlab.android.iab.v3:library:1.0.44' itslef? as i have not updated since January.
also this was the link suggested in the warning.. 
https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html
please help.

**Comment by kurtsergey** [comment]
#404

**Comment by ysnsyhn** [comment]
You may continue with this tutorial. It works fine. He is selling a snippet of code for 2$ and the inapp purchase works perfect again.
https://www.youtube.com/watch?v=0zp7Ho3eYeI&ab_channel=SharCourse
