### ISSUE TITLE
getSubscriptionDetails() returns old price

### ISSUE THREAD

**Issue by c0dehunter** [anjlab/android-inapp-billing-v3#426]
This is not in production yet, just testing. I made a subscription a few weeks ago and the price was indeed 5.49 EUR. Now I changed the price in Google Play Console (a few hours ago) to 3.99 EUR, but I am still getting the old price:

![image](https://user-images.githubusercontent.com/1484658/64863680-ba606100-d635-11e9-8ec6-ce1b111e31d7.png)

However, native dialog later shows correct price:

![image](https://user-images.githubusercontent.com/1484658/64863766-f1367700-d635-11e9-8589-94135b99eb6e.png)

I call loadOwnedPurchasesFromGoogle always on start:

```
 @Override
    public void onBillingInitialized() {
        if(bp != null && bp.loadOwnedPurchasesFromGoogle()) {
           ...
```

Should I wait longer or what's wrong? I reinstalled the app and it's the same!

**Comment by c0dehunter** [comment]
Update: the prices have now updated after waiting a bit longer!

**Comment by froozeapp** [comment]
Mind sharing your code on how you get the price? Mine always returns null e.G the App crashes.

**Comment by c0dehunter** [comment]
I would advise you to debug why it crashes (e.g., is BillingProccessor null?). It should work by calling `bp.getSubscriptionListingDetails("subscription_id")` and then checking the 7priceValue` field.

**Comment by froozeapp** [comment]
I'm an idiot, forgot to put it in onBillingInitialized()
