### ISSUE TITLE
Warning in google play console - Google Play Developer API version 3

### ISSUE THREAD

**Issue by avihyacohen** [anjlab/android-inapp-billing-v3#439]
I uploaded my apk to Alpha test and I get this warning :
**ACTION REQUIRED: Your server-side billing confirmations will stop working on December 1, 2019 Your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available, and any calls to these versions will fail. Update to version 3 before this date. Note that this is not related to the AIDL/Billing Library deprecation**

I use this library with version 1.1.0.
What I can do to solve this ??

**Comment by serggl** [comment]
Library was upgraded. See https://github.com/anjlab/android-inapp-billing-v3/pull/497
