### ISSUE TITLE
Refunded orders (getPurchaseState)

### ISSUE THREAD

**Issue by frmz** [anjlab/android-inapp-billing-v3#44]
Hi, after reading this:
http://stackoverflow.com/questions/15762370/does-google-play-in-app-billing-version-3-support-refunds
And this:
http://blog.blundell-apps.com/simple-inapp-billing-payment-v3/

I came to the conclusion that there is a way to understand if an order is purchased or refunded, since i am refunding quite often and i dont want those user to still be "pro" forever, is there any way to get this state with this library (which i love btw)?

Thanks!

**Comment by serggl** [comment]
Ok, with this one (#63) pull request merged, you can try to play in on your own. From my tests I never got some changes in `purchaseState` after cancelling/refunding
