### ISSUE TITLE
Migration to Google Play billing

### ISSUE THREAD

**Issue by fluiddot** [anjlab/android-inapp-billing-v3#441]
I saw that this library uses `com.android.vending.billing.IInAppBillingService` for the billing process and after checking the documentation (https://developer.android.com/google/play/billing/api#purchase) I'm a bit concerned about the red warning Google is giving regarding the deprecation of AIDL.

![Screenshot 2019-12-13 at 17 07 09](https://user-images.githubusercontent.com/14905380/70814071-05bc1400-1dcb-11ea-98d0-f57231e572d5.png)

Is there any plan to migrate to `Google Play billing` as it states in the warning?
https://developer.android.com/google/play/billing/billing_library_overview

Thanks!

**Comment by mikemike396** [comment]
Any update on this?

**Comment by Stupidman22** [comment]
Anyone update this .... ?

**Comment by shadowwalkersteam** [comment]
Do you have any plan to migrate the project to Google Play Billing Library?

**Comment by c0dehunter** [comment]
This is probably a stupid question, but there are other stupid users like me.

Why not just use Google Play Billing Library directly? Why do we need android-inapp-billing-v3 at all?

**Comment by mustii82** [comment]
Guys are you using the latest version of this library?

**Comment by Stupidman22** [comment]
> not just use Google Play Billing Library directly?

:)) We are lazy dev

**Comment by virusman** [comment]
Hasn't it already migrated to Google Play Billing since #411 ?

**Comment by akhileshsharma** [comment]
I guess issue of migration to google play billing library should be taken care of on Priority as AIDL is deprecated. Moving this billing library to latest google play billing library might clean up many of the pending issues. 

Any plans to move to new google library?

**Comment by dayron9110** [comment]
News?

**Comment by Pulo-lab** [comment]
Is it worth worrying? Or has it already been updated?

**Comment by mk35429** [comment]
Any update on this.

**Comment by akshaaatt** [comment]
I have made an Android Library to manage Google Play Billing, In App Purchases and Subscriptions with just a few lines of code.
Check it out and be sure to star the project if you liked my contribution :)

https://github.com/akshaaatt/Google-IAP

**Comment by serggl** [comment]
Library was upgraded. See https://github.com/anjlab/android-inapp-billing-v3/pull/497
