### ISSUE TITLE
[FEATURE][ACTION REQUIRED] Account Hold and Restore mandatory by 1 Nov 2020

### ISSUE THREAD

**Issue by Duna** [anjlab/android-inapp-billing-v3#448]
https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html

Account hold and Restore mandatory  - feature request mandatory 

Unless get app banned from Play Store

**Comment by shravanvinu** [comment]
hi, i tried enabling "pause" feature.. but subscription status still returns true , and subscription will still continue.. 
pple will misuse it if they come across this loophole.

**Comment by danielcshn** [comment]
I think it is simpler to implement deep links: https://developer.android.com/google/play/billing/subs#deep-link 
With that you meet the requirements of Google Play.
Google wants users to know that they can manage their subscriptions.

You can find example code for subscription link logic in the [Classy Taxi sample app](https://github.com/android/play-billing-samples/blob/52f85ddb6acc019b6b405ca68956d698ca96d640/ClassyTaxiJava/app/src/main/java/com/example/android/classytaxijava/ui/MainActivity.java#L119-L136).

**Comment by Duna** [comment]
> I think it is simpler to implement deep links: https://developer.android.com/google/play/billing/subs#deep-link
> With that you meet the requirements of Google Play.
> Google wants users to know that they can manage their subscriptions.
> 
> You can find example code for subscription link logic in the [Classy Taxi sample app](https://github.com/android/play-billing-samples/blob/52f85ddb6acc019b6b405ca68956d698ca96d640/ClassyTaxiJava/app/src/main/java/com/example/android/classytaxijava/ui/MainActivity.java#L119-L136).

Also I guess also the Real-time developer notifications MUST be implemented to handle hold and restoration events

**Comment by agGitHub** [comment]
Hi. Anybody could write a detailed tutorial in order to explain how to handle all this mess with RTDN, Pub/Sub, a potential backend server, etc... Thanks a lot !

**Comment by SUKI-Huang** [comment]
Please support v3
https://developer.android.com/google/play/billing/integrate
due to `these features from optional to either mandatory or on by default starting on November 1, 2020`
https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html

**Comment by RozeKurhy** [comment]
@Duna 
Hi! 

I have one question. Shouldn't this feature set up subscriptions on Google Play and handle RTDN on the backend? Need to add features in this billing library?

Thanks!

**Comment by dayron9110** [comment]
> Soporte v3
> https://developer.android.com/google/play/billing/integrate
> debido a `these features from optional to either mandatory or on by default starting on November 1, 2020`
> [https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain- subscribers.html](https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html)

Any updates?

**Comment by Duna** [comment]
Since there is no update on this feature, I think we should abandon this library and all move to RevenueCat. It is free and has also purchases backend. https://docs.revenuecat.com/discuss/5ef22b6e0687d10056a985f0

**Comment by Duna** [comment]
SkuDetails - should be updated with new enum flag: **status** wich should have **on hold** information

**Comment by VuHaiAn** [comment]
Please ask have any updates for this problem yet?

**Comment by agGitHub** [comment]
This thread might help: https://github.com/android/play-billing-samples/issues/373#issuecomment-701660996

**Comment by Duna** [comment]
Actually looking into InAppPurchases V3, I figured out that the SDK is very simple and IPC not needed anymore since GTeam did it the library similar to this one.
I dropped this lib and easily replaced with official V3 lib from Android (2 hours of work)
The only thing extra to be done is to acknowledge the unconsumable purchases.

**Comment by hatimmts** [comment]
Do free Apps should implement this update??

**Comment by rowie90** [comment]
> Should free Apps implement this update too??

That´s a big question for me. In my opinion it`s an impertinence that i have to implement this things altough i have not any in-app products - the whole app is free. I did not found a "2-line" solution for it yet und must read the complete introduction of the play billing system to fix it without any use of it - a massive waste of time.

**Comment by juicechu** [comment]
The article say “Here’s everything that is changing about the subscriptions platform”. So i think you have to implement only if your app use google subscriptions

**Comment by Duna** [comment]
Whay a dumb sentence is that :  "if your app use google subscriptions""
What is the purpose of this library if not In-App Purchases?

**Comment by juicechu** [comment]
I mean that you don't need to implement,  if your app don't use google subscriptions and only use consume product,

**Comment by Duna** [comment]
Account Hold and Restore -  not mandatory if not having subscription server that is handling onhold subscriptions.
