### ISSUE TITLE
SkuDetails in Debug Mode

### ISSUE THREAD

**Issue by shahkarraza001** [anjlab/android-inapp-billing-v3#451]
**Question: How to add subscription ids for Debug purpose to get SkuDetails.?**

I want to get subscription plan details in debug mode. While i have called
 `SkuDetails subs = bp.getSubscriptionListingDetails(SUBSCRIPTION_ID);`
but it always return null in debug. While i have run the sample project of this library, and **SUBSCRIPTION_ID = "com.anjlab.test.iab.subs1";** always rutrns value , once the billing process is initialized. I am wondering how to do this.

**Comment by Jhonatan-Moreira** [comment]
Hi, @shahkarraza001, i have a similar problem, null is always returned, who you do ?

**Comment by shahkarraza001** [comment]
@Jhonatan-Moreira i have changed the library version to 1.1.0 , its working fine
