### ISSUE TITLE
[MANDATORY] Acknowledge purchases by 1 November

### ISSUE THREAD

**Issue by Duna** [anjlab/android-inapp-billing-v3#455]
From 1st of November, all purchases must be acknowledged. If not acknowledged in 3 days prior purchases the purchase is cancelled automatically and the money refunded.

https://stackoverflow.com/questions/56585626/how-to-acknowledge-in-app-purchases-in-android

This lib should be updated, please...

**Comment by RozeKurhy** [comment]
This function can be used from BL2, but it seems to be impossible in this library. There is no library update these days.

I was also in trouble because of this issue. Fortunately, the acknowledge issue has been resolved because the backend team handled the app in my service.

**Comment by Duna** [comment]
I think FORK the project is the way

**Comment by serggl** [comment]
PRs here are also welcome

**Comment by RozeKurhy** [comment]
> PRs here are also welcome

Hi, serggl!

I am getting a lot of help thanks to your library. Always thank you!!

I wonder if you have any plans to upgrade this library to BL3. This is because, as you know, Google will force the use of BL3 from next year.

Should this library be updated only by PR due to your personal work?

**Comment by serggl** [comment]
At the moment, I don't do any Android development and I don't have any apps to maintain using this library.
I do have time to review and merge PRs to this project, but I don't plan to do any more development work here by myself.

This is an open source project and community should support it, thats why I always say PRs are welcome. 

You can always fork this project @Duna - there is no problem with this, just don't forget to to share you changes back. People here would really appreciate this

**Comment by Duna** [comment]
**Note:** Acknowledgement is not required when using a version of the Google Play Billing Library prior to 2.0.

**Comment by Duna** [comment]
Actually looking into InAppPurchases V3, I figured out that the SDK is very simple and IPC not needed anymore since GTeam did it the library similar to this one.
I dropped this lib and easily replaced with official V3 lib from Android (2 hours of work)
The only thing extra to be done is to acknowledge the unconsumable purchases.
