### ISSUE TITLE
Can not get proper SubscriptionListingDetails.

### ISSUE THREAD

**Issue by gbhargavv** [anjlab/android-inapp-billing-v3#467]
I set 999 in InApp Subscription but get price 1000 from SubscriptionListingDetails. How can i fix this issue?
- i use 'com.anjlab.android.iab.v3:library:1.0.44'.

**Comment by akshaaatt** [comment]
Try updating to 1.1.0 version

**Comment by gbhargavv** [comment]
@akshaaatt Thank you
