### ISSUE TITLE
Billing Library version 3 or newer.

### ISSUE THREAD

**Issue by yasdeveloper** [anjlab/android-inapp-billing-v3#478]
Reminder: Starting on August 2, 2021, all new apps must use Billing Library version 3 or newer. By November 1, 2021, all updates to existing apps must use Billing Library version 3 or newer. Learn more.

**Comment by mrgallme** [comment]
Joining the question! 
Need v3 release

**Comment by imayka** [comment]
Joining
Please upgrade

**Comment by mcsong** [comment]
Joining
Please~~

**Comment by paktech1** [comment]
please upgrade.

**Comment by conanlovevit** [comment]
Same warning. Pls upgrade library

**Comment by kzlsnn** [comment]
Joining please.

**Comment by rajkumar02** [comment]
Please upgrade!

**Comment by cellojaan** [comment]
@serggl wake up bro

**Comment by jatin-lakhani** [comment]
Please update v3 soon..

**Comment by lau1944** [comment]
Me too following

**Comment by Desintegrator** [comment]
+1

**Comment by AroundPixels** [comment]
It will be great 👯‍♀️

**Comment by AhmadSaeed68** [comment]
Joining the question!
Need release

**Comment by yasirabid96** [comment]
Pls upgrade library

**Comment by ShaheryarMalik007** [comment]
Joining the question!
please update

**Comment by VittoriDavide** [comment]
+1

**Comment by devravi** [comment]
+1

**Comment by akshaaatt** [comment]
I have made an Android Library to manage Google Play Billing, In App Purchases and Subscriptions with just a few lines of code.
Check it out and be sure to star the project if you liked my contribution :)

https://github.com/akshaaatt/Google-IAP

**Comment by conanlovevit** [comment]
+1

**Comment by BilalRammal** [comment]
+1

**Comment by ZeeshanArid** [comment]
Please update +1

**Comment by needz** [comment]
+1

**Comment by ashutoshgngwr** [comment]
IMO, this library isn't needed anymore. Google Play billing v2 offered a very low-level AIDL, but v3 offers a Kotlin/Java API. The AIDL API required a lot of boilerplate code for handling raw data and making requests. The Kotlin/Java API offered by v3 takes care of that, which is also one of the pain points that this library addressed for v2. Unlike v2, v3 also [queries Play Store's cache on querying purchases](https://developer.android.com/reference/com/android/billingclient/api/BillingClient#querypurchases). A major chunk of this library was dedicated to maintaining this cache.

The v3 library doesn't address verifying purchases. You can copy-paste the [Security](https://github.com/anjlab/android-inapp-billing-v3/blob/master/library/src/main/java/com/anjlab/android/iab/v3/Security.java) class for that. Your `licenseKey` is the public key for verifying purchases. `productId`, `purchaseData` and `dataSignature` are returned by [Purchase#getSku()](https://developer.android.com/reference/com/android/billingclient/api/Purchase#getsku), [Purchase#getOriginalJson()](https://developer.android.com/reference/com/android/billingclient/api/Purchase#getoriginaljson) and [Purchase#getSignature()](https://developer.android.com/reference/com/android/billingclient/api/Purchase#getsignature) respectively.

https://github.com/anjlab/android-inapp-billing-v3/blob/23b702219e7449e99ba94ace21cbe2cdb6eb6e8d/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java#L173-L177

https://github.com/anjlab/android-inapp-billing-v3/blob/23b702219e7449e99ba94ace21cbe2cdb6eb6e8d/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java#L1009-L1024

On a side note, you are now required to [either acknowledge or consume all purchases](https://developer.android.com/google/play/billing/integrate#process). You also need to [handle pending purchases](https://developer.android.com/google/play/billing/integrate#ooap) that may transition to the purchased state while the user is away from your app.

**Comment by dzungpv** [comment]
After trying to make this project compatible with v3, I gave up and using only the v3 itself, It is not complicate to use, you can follow this sample https://medium.com/@programtown/how-to-make-in-app-purchase-in-android-using-google-play-billing-library-updated-library-3-0-1-72e0b1fd43d5 or more advance sample of Google ClassyTaxiJava https://github.com/android/play-billing-samples/blob/main/ClassyTaxiJava/app/src/main/java/com/sample/android/classytaxijava/billing/BillingClientLifecycle.java , change the **BillingClient.SkuType.SUBS**  to **BillingClient.SkuType.INAPP** for use with non subscription

**Comment by nukix** [comment]
Please upgrade

**Comment by paktech1** [comment]
thanks to @dzungpv i was able to update my library to 3.0.1, still testing, will comment after testing.

**Comment by Mahadev-code** [comment]
Billing Library v-3
Demo Application :- https://github.com/Mahadev-code/AndroidInAppPurchase

Source code also tested on Google Play store

**Comment by ashutoshgngwr** [comment]
I wrote a companion library to tackle the quirks of the new Google Play Billing API. I am currently working on the documentation and maven central deployment, but the sample is ready and clients can consume the library via [Jitpack](https://jitpack.io).

The library offers the following new features.

1. Handles pending purchase synchronisation (new in Google Play Billing)
2. Automatically verified purchase data if the license key is provided
3. Offers features to auto acknowledge and consume purchases
4. Supports auto-retry mechanism if the connection to billing service is lost
5. Closely mimics the API offered by anjlab's library

https://github.com/ashutoshgngwr/plutus-android

**Comment by wicaodian** [comment]
Bump, Please update

**Comment by Cand3h** [comment]
Any idea what to do? It seems that there won't be any update.

**Comment by paktech1** [comment]
class BillingProvider constructor(
    val context: Context,
    val license:String,
    val productsList:List<String>,
    var purchaseStatusUpdate: ((purchases: List<BillingItem>?) -> Unit)
) : PurchasesUpdatedListener {


    init {
        initBillingClient()
    }

    //var purchaseStatusUpdate: ((productId:String,status:Boolean)->Unit)? = null

    private var billingClient: BillingClient? = null


    private fun initBillingClient() {
        billingClient = BillingClient.newBuilder(context)
            .enablePendingPurchases().setListener(this).build()
        billingClient?.startConnection(object : BillingClientStateListener {
            override fun onBillingSetupFinished(billingResult: BillingResult) {
                if (billingResult.responseCode == BillingClient.BillingResponseCode.OK) {
                    val queryPurchase = billingClient?.queryPurchases(BillingClient.SkuType.INAPP)
                    val queryPurchases =
                        queryPurchase?.purchasesList
                    if (queryPurchases != null && queryPurchases.size > 0) {
                        handlePurchases(queryPurchases)
                    } else {
                        purchaseStatusUpdate(null)
                    }
                }
            }

            override fun onBillingServiceDisconnected() {
                purchaseStatusUpdate(null)
            }
        })
    }


    open fun handlePurchases(purchases: List<Purchase>) {
        val billingItems = ArrayList<BillingItem>()
        for (purchase in purchases) {
            //if item is purchased
            if (productsList.contains(purchase.sku) && purchase.purchaseState == Purchase.PurchaseState.PURCHASED) {
                if (!verifyValidSignature(purchase.originalJson, purchase.signature)) {
                    // Invalid purchase
                    // show error to user
                    billingItems.add(BillingItem(purchase.sku, false))
                    context.showMessege("Error : Invalid Purchase")
                    return
                }
                // else purchase is valid
                //if item is purchased and not acknowledged
                if (!purchase.isAcknowledged) {
                    val acknowledgePurchaseParams =
                        AcknowledgePurchaseParams.newBuilder()
                            .setPurchaseToken(purchase.purchaseToken)
                            .build()
                    billingClient?.acknowledgePurchase(acknowledgePurchaseParams) {
                        val result = (it.responseCode == BillingClient.BillingResponseCode.OK)
                        purchaseStatusUpdate(listOf(BillingItem(purchase.sku, result)))
                    }
                } else {
                    billingItems.add(BillingItem(purchase.sku, true))
                }
            } else if (productsList.contains(purchase.sku) && purchase.purchaseState == Purchase.PurchaseState.PENDING) {
                context.showMessege("Purchase is Pending. Please complete Transaction")
                billingItems.add(BillingItem(purchase.sku, false))
            } else if (productsList.contains(purchase.sku) && purchase.purchaseState == Purchase.PurchaseState.UNSPECIFIED_STATE) {
                billingItems.add(BillingItem(purchase.sku, false))
            }

        }
        purchaseStatusUpdate(billingItems)
    }


    private fun verifyValidSignature(
        signedData: String,
        signature: String
    ): Boolean {
        return try {
            // To get key go to Developer Console > Select your app > Development Tools > Services & APIs.
            Security.verifyPurchase(license, signedData, signature)
        } catch (e: IOException) {
            false
        }
    }

    override fun onPurchasesUpdated(
        billingResult: BillingResult,
        purchases: MutableList<Purchase>?
    ) {
        if (billingResult.getResponseCode() == BillingClient.BillingResponseCode.OK && purchases != null) {
            handlePurchases(purchases)
        } else if (billingResult.getResponseCode() == BillingClient.BillingResponseCode.ITEM_ALREADY_OWNED) {
            val queryAlreadyPurchasesResult: Purchase.PurchasesResult? =
                billingClient?.queryPurchases(
                    BillingClient.SkuType.INAPP
                )
            val alreadyPurchases: List<Purchase>? = queryAlreadyPurchasesResult?.getPurchasesList()
            alreadyPurchases?.let { handlePurchases(it) }
        } else if (billingResult.getResponseCode() == BillingClient.BillingResponseCode.USER_CANCELED) {
            context.showMessege("Purchase Canceled")
        } else {
            context.showMessege(
                "Error " + billingResult.getDebugMessage()
            )
        }
    }

    private fun initiatePurchase(activity: Activity, itemId: String) {
        val skuList = ArrayList<String>()
        skuList.add(itemId)
        val params = SkuDetailsParams.newBuilder()
        params.setSkusList(skuList).setType(BillingClient.SkuType.INAPP)
        billingClient?.querySkuDetailsAsync(
            params.build()
        ) { billingResult, skuDetailsList ->
            if (billingResult.responseCode === OK) {
                if (skuDetailsList != null && skuDetailsList.size > 0) {
                    val flowParams = BillingFlowParams.newBuilder()
                        .setSkuDetails(skuDetailsList[0])
                        .build()
                    billingClient?.launchBillingFlow(activity, flowParams)
                } else {
                    //try to add item/product id "purchase" inside managed product in google play console
                    context.showMessege(
                        "Purchase Item not Found"
                    )
                }
            } else {
                context.showMessege(
                    " Error " + billingResult.debugMessage
                )
            }
        }
    }

     fun requsetPaymment(activity: Activity, itemId: String) {
        if (billingClient?.isReady==true) {
            initiatePurchase(activity,itemId)
        } else {
            billingClient =
                BillingClient.newBuilder(context).enablePendingPurchases().setListener(this).build()
            billingClient?.startConnection(object : BillingClientStateListener {
                override fun onBillingSetupFinished(billingResult: BillingResult) {
                    if (billingResult.responseCode === OK) {
                        initiatePurchase(activity,itemId)
                    } else {
                        context.showMessege(
                            "Error " + billingResult.debugMessage)
                    }
                }

                override fun onBillingServiceDisconnected() {

                }
            })
        }
    }

}

data class BillingItem(val productId: String, val status: Boolean)

**Comment by paktech1** [comment]
class BillingProvider constructor(
    val context: Context,
    val license:String,
    val productsList:List<String>,
    var purchaseStatusUpdate: ((purchases: List<BillingItem>?,isRestore:Boolean) -> Unit)
) : PurchasesUpdatedListener {


    init {
        initBillingClient()
    }

    //var purchaseStatusUpdate: ((productId:String,status:Boolean)->Unit)? = null

    private var billingClient: BillingClient? = null


    private fun initBillingClient() {
        billingClient = BillingClient.newBuilder(context)
            .enablePendingPurchases().setListener(this).build()
        billingClient?.startConnection(object : BillingClientStateListener {
            override fun onBillingSetupFinished(billingResult: BillingResult) {
                if (billingResult.responseCode == BillingClient.BillingResponseCode.OK) {
                    val queryPurchase = billingClient?.queryPurchases(BillingClient.SkuType.INAPP)
                    val queryPurchases =
                        queryPurchase?.purchasesList
                    if (queryPurchases != null && queryPurchases.size > 0) {
                        handlePurchases(queryPurchases,true)
                    } else {
                        purchaseStatusUpdate(null,false)
                    }
                }
                else
                    purchaseStatusUpdate(null,false)
            }

            override fun onBillingServiceDisconnected() {
                purchaseStatusUpdate(null,false)
            }
        })
    }


    open fun handlePurchases(purchases: List<Purchase>,isRestore:Boolean= false) {
        val billingItems = ArrayList<BillingItem>()
        for (purchase in purchases) {
            //if item is purchased
            if (productsList.contains(purchase.sku) && purchase.purchaseState == Purchase.PurchaseState.PURCHASED) {
                if (!verifyValidSignature(purchase.originalJson, purchase.signature)) {
                    // Invalid purchase
                    // show error to user
                    billingItems.add(BillingItem(purchase.sku, false))
                    context.showMessege("Error : Invalid Purchase")
                    return
                }
                // else purchase is valid
                //if item is purchased and not acknowledged
                if (!purchase.isAcknowledged) {
                    billingItems.add(BillingItem(purchase.sku, true))
                    val acknowledgePurchaseParams =
                        AcknowledgePurchaseParams.newBuilder()
                            .setPurchaseToken(purchase.purchaseToken)
                            .build()
                    billingClient?.acknowledgePurchase(acknowledgePurchaseParams) {
//                        val result = (it.responseCode == BillingClient.BillingResponseCode.OK)
//                        purchaseStatusUpdate(listOf(BillingItem(purchase.sku, result)))
                         }
                } else {

                }
                billingItems.add(BillingItem(purchase.sku, true))
            } else if (productsList.contains(purchase.sku) && purchase.purchaseState == Purchase.PurchaseState.PENDING) {
                context.showMessege("Purchase is Pending. Please complete Transaction")
                billingItems.add(BillingItem(purchase.sku, false))
            } else if (productsList.contains(purchase.sku) && purchase.purchaseState == Purchase.PurchaseState.UNSPECIFIED_STATE) {
                billingItems.add(BillingItem(purchase.sku, false))
            }

        }
        purchaseStatusUpdate(billingItems,isRestore)
    }


    private fun verifyValidSignature(
        signedData: String,
        signature: String
    ): Boolean {
        return try {
            // To get key go to Developer Console > Select your app > Development Tools > Services & APIs.
            Security.verifyPurchase(license, signedData, signature)
        } catch (e: IOException) {
            false
        }
    }

    override fun onPurchasesUpdated(
        billingResult: BillingResult,
        purchases: MutableList<Purchase>?
    ) {
        if (billingResult.getResponseCode() == BillingClient.BillingResponseCode.OK && purchases != null) {
            handlePurchases(purchases)
        } else if (billingResult.getResponseCode() == BillingClient.BillingResponseCode.ITEM_ALREADY_OWNED) {
            val queryAlreadyPurchasesResult: Purchase.PurchasesResult? =
                billingClient?.queryPurchases(
                    BillingClient.SkuType.INAPP
                )
            val alreadyPurchases: List<Purchase>? = queryAlreadyPurchasesResult?.getPurchasesList()
            alreadyPurchases?.let { handlePurchases(it) }
        } else if (billingResult.getResponseCode() == BillingClient.BillingResponseCode.USER_CANCELED) {
            context.showMessege("Purchase Canceled")
        } else {
            context.showMessege(
                "Error " + billingResult.getDebugMessage()
            )
        }
    }

    private fun initiatePurchase(activity: Activity, itemId: String) {
        val skuList = ArrayList<String>()
        skuList.add(itemId)
        val params = SkuDetailsParams.newBuilder()
        params.setSkusList(skuList).setType(BillingClient.SkuType.INAPP)
        billingClient?.querySkuDetailsAsync(
            params.build()
        ) { billingResult, skuDetailsList ->
            if (billingResult.responseCode === BillingClient.BillingResponseCode.OK) {
                if (skuDetailsList != null && skuDetailsList.size > 0) {
                    val flowParams = BillingFlowParams.newBuilder()
                        .setSkuDetails(skuDetailsList[0])
                        .build()
                    billingClient?.launchBillingFlow(activity, flowParams)
                } else {
                    //try to add item/product id "purchase" inside managed product in google play console
                    context.showMessege(
                        "Purchase Item not Found"
                    )
                }
            } else {
                context.showMessege(
                    " Error " + billingResult.debugMessage
                )
            }
        }
    }

     fun requsetPaymment(activity: Activity, itemId: String) {
        if (billingClient?.isReady==true) {
            initiatePurchase(activity,itemId)
        } else {
            billingClient =
                BillingClient.newBuilder(context).enablePendingPurchases().setListener(this).build()
            billingClient?.startConnection(object : BillingClientStateListener {
                override fun onBillingSetupFinished(billingResult: BillingResult) {
                    if (billingResult.responseCode === BillingClient.BillingResponseCode.OK) {
                        initiatePurchase(activity,itemId)
                    } else {
                        context.showMessege(
                            "Error " + billingResult.debugMessage)
                    }
                }

                override fun onBillingServiceDisconnected() {

                }
            })
        }
    }

}

data class BillingItem(val productId: String, val status: Boolean)

**Comment by paktech1** [comment]
kindly use the above helper class like this:

   private fun startBillingProcess() {
        billinProvider = BillingProvider(this,BillingData.APP_LICENSE,BillingData.listProducts){itemsList,isRestore->
            itemsList?.forEach {
                if(it.productId==BillingData.REMOVE_ADS_ID && it.status)
                    preferenceManager.removeAds = true
            }
       
        }
    }

**Comment by UlisesSwingU** [comment]
please upgrade!

**Comment by lilmnm-kamikaze-** [comment]
for you to get it to update to V3 you just need to edit the [build.gradel](https://github.com/anjlab/android-inapp-billing-v3/blob/23b702219e7449e99ba94ace21cbe2cdb6eb6e8d/library/build.gradle#L39) and edit line 39 from `implementation 'com.android.billingclient:billing:2.0.1'` to `implementation 'com.android.billingclient:billing:3.0.3'`

**Comment by nihp** [comment]
Any sample for the [BillingClient](https://developer.android.com/reference/com/android/billingclient/api/BillingClient)?

**Comment by ashutoshgngwr** [comment]
> Any sample for the [BillingClient](https://developer.android.com/reference/com/android/billingclient/api/BillingClient)?

It may not be exactly what you want. https://github.com/ashutoshgngwr/noice/blob/7508bf10678ad6bfac2fd37762668e4180396bb5/app/src/playstore/java/com/github/ashutoshgngwr/noice/provider/RealBillingProvider.kt

**Comment by nihp** [comment]
@ashutoshgngwr I am using java

**Comment by Mahadev-code** [comment]
> Any sample for the [BillingClient](https://developer.android.com/reference/com/android/billingclient/api/BillingClient)?

Android Billing Library v-4+

Source Code :- https://github.com/Mahadev-code/Android-inApp-Billing

**Comment by serggl** [comment]
Library was upgraded. See https://github.com/anjlab/android-inapp-billing-v3/pull/497

**Comment by sangolariel** [comment]
+1

**Comment by ysnsyhn** [comment]
You may continue with this tutorial. It works fine. He is selling a snippet of code for 2$ and the inapp purchase works perfect again.
https://www.youtube.com/watch?v=0zp7Ho3eYeI&ab_channel=SharCourse
