### ISSUE TITLE
Error Code 102

### ISSUE THREAD

**Issue by midou221** [anjlab/android-inapp-billing-v3#481]
I'm use Alpha release
When I try to subscribe I always get this error (102)
I don't understand what caused it and how can I fix it
this my code:

`
   subscribeBtn = findViewById(R.id.purchedbtn);
        subscribeBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                bp.subscribe(ActivityPurched.this,subScribe_id);
            }
        });

        if(!BillingProcessor.isIabServiceAvailable(this)) {
            showToast("In-app billing service is unavailable, please upgrade Android Market/Play to version >= 3.9.16");
        }

        bp = new BillingProcessor(this,LICENSE_KEY,MERCHANT_ID, new BillingProcessor.IBillingHandler() {
            @Override
            public void onProductPurchased(@NonNull String productId, @Nullable TransactionDetails details) {
                showToast("onProductPurchased: " + productId);
                bp.consumePurchase(productId);
            }
            @Override
            public void onBillingError(int errorCode, @Nullable Throwable error) {
                showToast("onBillingError: " + Integer.toString(errorCode));
            }
            @Override
            public void onBillingInitialized() {
                showToast("onBillingInitialized");
                readyToPurchase = true;

            }
            @Override
            public void onPurchaseHistoryRestored() {
                showToast("onPurchaseHistoryRestored");
                for(String sku : bp.listOwnedProducts())
                    Log.d("LOG_TAG", "Owned Managed Product: " + sku);
                for(String sku : bp.listOwnedSubscriptions())
                    Log.d("LOG_TAG", "Owned Subscription: " + sku);

            }
        });

        if(bp.isSubscribed(subScribe_id)){
            subscribeBtn.setText("thank you for subscribe");
        }

        if (!readyToPurchase) {
            showToast("Billing not initialized.");
            return;
        }

    @Override
    public void onDestroy() {
        if (bp != null)
            bp.release();
        super.onDestroy();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {

        if (!bp.handleActivityResult(requestCode, resultCode, data))
            super.onActivityResult(requestCode, resultCode, data);
    }
`

logcat:
2021-03-23 13:34:22.690 5347-5347/? E/IABUtil/Security: Signature verification failed.
2021-03-23 13:34:22.690 5347-5347/? E/iabv3: Public key signature doesn't match!

but I use the same public key from monetization setup
and I don't think i pasted it wrong

**Comment by midou221** [comment]
I switched to Google Play Billing
[](https://github.com/android/play-billing-samples)

**Comment by pinpong** [comment]
Had the same error and recognized that my license key changed after migrating to new app signature.
