### ISSUE TITLE
Mail from Google: "Play Billing Library version deprecation" 

### ISSUE THREAD

**Issue by ForestRingGames** [anjlab/android-inapp-billing-v3#484]
We received the following mail from Google:

> We've detected that this app is using an old version of Google Play Billing. From 1 November 2021, all app updates must use Billing Library version 3 or newer.
> 
> Action required: Please verify that your publicly available APKs are updated to the latest version of the Play Billing Library. This includes any APK or App Bundle rolled out in production.

1) Does the latest version of android-inapp-billing-v3 support this? 
2) If yes, when was it updated to support it? 
3) Did anybody else also receive that mail?

**Comment by Mahadev-code** [comment]
Use Billing Library above v-3

Demo Source code:- https://github.com/Mahadev-code/AndroidInAppPurchase

**Comment by ForestRingGames** [comment]
@Mahadev-code Thank you, but that's a different library, right? I'd like to keep using this library. Do you know if that's possible?

**Comment by Cand3h** [comment]
Any idea what to do? It seems that there won't be any update.

**Comment by ForestRingGames** [comment]
@Cand3h Not yet, no.

**Comment by serggl** [comment]
Library was upgraded. See https://github.com/anjlab/android-inapp-billing-v3/pull/497
