### ISSUE TITLE
Confirmation about google policy for billing in 3.0

### ISSUE THREAD

**Issue by najam-amfnrh9** [anjlab/android-inapp-billing-v3#485]
I have concerns about will this support google latest requirement::: 
Reminder: Starting on August 2, 2021, all new apps must use Billing Library version 3 or newer. By November 1, 2021, all updates to existing apps must use Billing Library version 3 or newer. 
Reference: https://developer.android.com/google/play/billing/integrate...

**Comment by Mahadev-code** [comment]
Use Billing Library above v-3

Demo application :- https://github.com/Mahadev-code/AndroidInAppPurchase

Source code tested on Google play store

**Comment by najam-amfnrh9** [comment]
Thanks for your response...

**Comment by ashutoshgngwr** [comment]
Duplicate of #478

**Comment by danieljr99048** [comment]
trash

**Comment by danieljr99048** [comment]
not work

**Comment by Cand3h** [comment]
Any idea what to do? It seems that there won't be any update.

**Comment by TariqMahmud** [comment]
> Source code tested on Google play store

will you not update this library?

**Comment by serggl** [comment]
Library was upgraded. See https://github.com/anjlab/android-inapp-billing-v3/pull/497
