### ISSUE TITLE
Android inapp billing v3 is not working (1.1.0)

### ISSUE THREAD

**Issue by danieljr99048** [anjlab/android-inapp-billing-v3#488]
It does not comply with the new Google Play policy 2021, after November goodbye.

update as soon as possible as many developers use.

**Comment by wicaodian** [comment]
Duplicate of #478

**Comment by Duna** [comment]
V3 my ass, this is v2

**Comment by Cand3h** [comment]
Any idea what to do? It seems that there won't be any update.

**Comment by Duna** [comment]
I did switch to google play purchase V3. It's pretty similar to this lib.

**Comment by serggl** [comment]
Library was upgraded. See https://github.com/anjlab/android-inapp-billing-v3/pull/497

**Comment by Duna** [comment]
Good work 👍 thanks
