### ISSUE TITLE
Introductory offer is not working

### ISSUE THREAD

**Issue by kksingla** [anjlab/android-inapp-billing-v3#489]
Introductory price is not showing, whenever we launch it is showing the regular price for every user.

Also, showing this subscription is not auto-renewable.
![WhatsApp Image 2021-05-10 at 8 14 07 PM](https://user-images.githubusercontent.com/18482328/117681896-3080e680-b1d0-11eb-8028-ed6d22b338fd.jpg)

**Comment by moisoni97** [comment]
I don't think you should use this library because despite it's advertised like V3 library, in fact is using old v2 aidl services which will be discontinued be Google in November or so.
