### ISSUE TITLE
Update Library

### ISSUE THREAD

**Issue by NaveenDevrani** [anjlab/android-inapp-billing-v3#498]
please update the library for android
google play store showing warning 
like 
"We've detected this app uses an unsupported version of Play billing. Please upgrade to Billing Library version 3 or newer to publish this app."

i also attached the screenshot for your reference
please check and update the billing library

<img width="960" alt="Screenshot 2021-10-22 at 4 44 22 PM" src="https://user-images.githubusercontent.com/37726754/138444938-ae642abf-4ce9-43ae-9e1c-436713b2e56d.png">

**Comment by serggl** [comment]
Upgraded. See https://github.com/anjlab/android-inapp-billing-v3/pull/497
