### ISSUE TITLE
Update library to v3 or v4

### ISSUE THREAD

**Issue by swapnil-gawali** [anjlab/android-inapp-billing-v3#499]
I am getting this message in the play store during the publishing update of the app.

**We've detected that this app is using an old version of Google Play Billing. From 1 November 2021, all app updates must use Billing Library version 3 or newer.

Action required: Please verify that your publicly available APKs are updated to the latest version of the Play Billing Library. This includes any APK or App Bundle rolled out in production.**

Within a week, updates from the older version are going to stop. Please update the library ASAP.

**Comment by serggl** [comment]
Upgraded. See https://github.com/anjlab/android-inapp-billing-v3/pull/497
