### ISSUE TITLE
billingProcessor.getSubscriptionsListingDetailsAsync always got Empty products list

### ISSUE THREAD

**Issue by ShawnLin013** [anjlab/android-inapp-billing-v3#508]
- which version of library you use: v2.0.2

After migrating to v2.0.2, billingProcessor.getSubscriptionsListingDetailsAsync always got `Empty products list`.
The issue is caused by the line 878 `getSkuDetailsAsync` in BillingProcessor.java. 
It could be fixed by replacing `if (productIdList != null && productIdList.size() > 0)` with `if (productIdList == null || productIdList.size() <= 0)` in. getSkuDetailsAsync().

Related code snippet of getSkuDetailsAsync()
```
private void getSkuDetailsAsync(final ArrayList<String> productIdList, String purchaseType,
									final ISkuDetailsResponseListener listener)
	{
		if (billingService == null || !billingService.isReady())
		{
			reportSkuDetailsErrorCaller("Failed to call getSkuDetails. Service may not be connected", listener);
			return;
		}
		if (productIdList != null && productIdList.size() > 0)
		{
			reportSkuDetailsErrorCaller("Empty products list", listener);
			return;
		}
```

**Comment by serggl** [comment]
ah, shoot...let me fix that

**Comment by serggl** [comment]
use 2.0.3
