### ISSUE TITLE
UPDATE: v5 API Upgrade Require

### ISSUE THREAD

**Issue by BhargavBhansali** [anjlab/android-inapp-billing-v3#527]

**Comment by horvathcsabalaszlo** [comment]
Hi,

Will be there any update issued for BillingClient v5?

**Comment by BhargavBhansali** [comment]
Nope Still not

**Comment by LeeSeungYongg** [comment]
Hi,

Well, then... Is v4 updated??

**Comment by NaveenDevrani** [comment]
<img width="1085" alt="Warring billing" src="https://github.com/anjlab/android-inapp-billing-v3/assets/37726754/aea7e35b-2a7b-4eba-a3f1-86df6acd1e54">

please update the library

**Comment by ysnsyhn** [comment]
You may continue with this tutorial. It works fine. He is selling a snippet of code for 2$ and the inapp purchase works perfect again.
https://www.youtube.com/watch?v=0zp7Ho3eYeI&ab_channel=SharCourse
