### ISSUE TITLE
Subscription expire date

### ISSUE THREAD

**Issue by ncanella** [anjlab/android-inapp-billing-v3#53]
How can i check if a subscription is expired?
When I call isSubscribed() it always return true, even if user has deleted the subscription.

**Comment by dfcarvalho** [comment]
Hi,
Two things:
1) If a user cancels a subscription, Google doesn't immediately revokes their access to the contents of that subscription. Google's In App Billing API will continue to say the user is subscribed until the end of that month's cycle. You can take a look at Google Play's Terms of Service for more information on this.
2) Take a look at this other issue: https://github.com/anjlab/android-inapp-billing-v3/issues/44

**Comment by serggl** [comment]
After subscription is canceled, its still active until the end of subscription period, so `loadOwnedPurchasesFromGoogle` wont affect the list of subscriptions untill that date.

**Comment by tobias-r** [comment]
I do have the same issue.

My subscription is cancelled and expired for over a day now. If I check via Google Server API, everything is returned correct and expired.

In the app however, isSubscribed is still _true_ and purchaseStatue is _PurchasedSuccessfully_.

I called loadOwnedPurchasesFromGoogle() and listOwnedSubscriptions() multiple times.

TransactionDetails.toString() return the correct date purchased.

Any help or ideas?

**Comment by didikeeLunaon** [comment]
so am i,how to check subscribe status after subscribe?
