### ISSUE TITLE
Future Support for Billing Library version 5 or newer

### ISSUE THREAD

**Issue by myinnos** [anjlab/android-inapp-billing-v3#539]
**Is this lib continuing to support further versions?**

We already started receiving the warning from the play store. 

> **Play Billing Library version deprecation**
> We've detected that this app is using an old version of Google Play Billing. From 1 November 2023, all app updates must use Billing Library version 5 or newer.
> 
> Action required: Please verify that your publicly available APKs are updated to the latest version of the Play Billing Library. This includes any APK or app bundle rolled out in production.

Awaiting the positive response.

**Comment by sarafdar** [comment]
Any solution for this issue?

**Comment by Ph03niX-X** [comment]
> Any solution for this issue?

I migrated to Google Play Billing Library 6. In addition, this library solved the problem with compatibility with Android 14

**Comment by paktech1** [comment]
@Ph03niX-X  your contribution is not accepted yet, waiting for an update.

**Comment by Ph03niX-X** [comment]
> @Ph03niX-X  your contribution is not accepted yet, waiting for an update.

I am not in the business of updating this library. I just migrated to the library from Google

https://developer.android.com/google/play/billing/integrate

**Comment by myinnos** [comment]
@Ph03niX-X you mean you deprecated this lib in your app and wrote your own integration for Google Play Billing Library 6?

**Comment by dnietotwonav** [comment]
I've seen this PR addressing this issue: https://github.com/anjlab/android-inapp-billing-v3/pull/544

The next week is the deadline for the current supported version (v4), _From 1 November 2023, all app updates must use Billing Library version 5 or newer_

Would be a new release version for this library this week?

**Comment by ysnsyhn** [comment]
You may continue with this tutorial. It works fine. He is selling a snippet of code for 2$ and the inapp purchase works perfect again.
https://www.youtube.com/watch?v=0zp7Ho3eYeI&ab_channel=SharCourse

**Comment by wicheda** [comment]
I believe if you have your gradle dependencies set up as:

`    
implementation 'com.anjlab.android.iab.v3:library:2.0.0'
implementation "com.android.billingclient:billing:5.1.0"
`

then it should all work and still be accepted by Google.

**Comment by cotfas** [comment]
As I see from 2.0.3 version there are still two commits that are not included.

![Screenshot 2023-12-07 at 22 36 23](https://github.com/anjlab/android-inapp-billing-v3/assets/3340367/75b1e5d0-ac19-4454-af6c-f9db34409d9c)

**Comment by cotfas** [comment]
I think this is the PR https://github.com/anjlab/android-inapp-billing-v3/pull/517

**Comment by Patriikk** [comment]
I intend to create a new version of this library based on the latest updates and enhancements.
