### ISSUE TITLE
iabv3﹕ resultCode = 0, responseCode = 2

### ISSUE THREAD

**Issue by AngelBob** [anjlab/android-inapp-billing-v3#57]
I am getting "Authentication is required. You need to sign in to your Google Account."
I have uploaded a Alpha apk to play and added the required items to the developer account.

I have tried this on two different devices, both only with one google account setup.

**Comment by AngelBob** [comment]
Seems it was an issue on Google's side

**Comment by venki0552** [comment]
Hi is this problem solved for you?
Please let me know fix for this process I am also facing the same problem.
