### ISSUE TITLE
Error code 102

### ISSUE THREAD

**Issue by ekzarov** [anjlab/android-inapp-billing-v3#58]
I`m trying to buy android.test.purchased (test product from google). And get error 102.
Here is my code:

@Override
    public void onBillingInitialized() {

        billingProcessor.consumePurchase("android.test.purchased");
        billingProcessor.purchase(this, "android.test.purchased");
    }

    @Override
    public void onProductPurchased(String productId, TransactionDetails details) {

        Toast.makeText(this, "onProductPurchased", Toast.LENGTH_LONG).show();
    }

    @Override
    public void onBillingError(int errorCode, Throwable error) {
        Toast.makeText(this, "Error code = " + errorCode, Toast.LENGTH_LONG).show();
    }

**Comment by LucasR93** [comment]
Can you tell, what was the issue?

**Comment by ekzarov** [comment]
BuildConfig.DEBUG was false.

if (BuildConfig.DEBUG){
   //handle test purchase not having signature
   if(productId.equals("android.test.purchased") && TextUtils.isEmpty(signature)){
      return true;
   }
}

**Comment by castrojr913** [comment]
The same thing, how can I manage this issue?

**Comment by castrojr913** [comment]
@ekzarov How can i test a purchase? Where do you add that code?
