### ISSUE TITLE
Why android-inapp-billing-v3 library needs two attempts to purchase android.test.purchased product?

### ISSUE THREAD

**Issue by tral** [anjlab/android-inapp-billing-v3#60]
Hello, I asked this on stackoverflow also, any ideas why it can happen?

http://stackoverflow.com/questions/28115156/why-android-inapp-billing-v3-library-needs-two-attempts-to-purchase-android-test

**Comment by serggl** [comment]
Hey, Im not sure what happened in your particular case. Error code 102 means 'Invalid signature', so maybe this helps for a further troubleshooting

**Comment by tral** [comment]
Looks like a Google's bug with Static Responses, check the most popular answer from here:
http://stackoverflow.com/questions/14600664/android-in-app-purchase-signature-verification-failed

**Comment by serggl** [comment]
that might be an issue. What I would recommend to you is to test using 'real' products and purchase them using a beta tester user account. Google doest charge money for such purchases. Thats how Im usually running tests. http://developer.android.com/google/play/billing/billing_testing.html

**Comment by tral** [comment]
yes, now I test my purchases this way too.
But I'am using your lib now and this issue is already hapenned.
As the dude from stackoverflow writes, I should "hack" Security.java, BUT I DON'T HAVE IT! I guess that you work with this file in your lib? Can you fix this issue in the lib by preventing use of android.test.ourchased for example?

Ohh.. And I'll think how to "consume" this product to remove this issue...

**Comment by ZiegenGIT** [comment]
I have the exact same problem. When purchasing something I get the Error Code 102, when pressing the button a second the time the onProductPurchased() method gets called. Also it says 
```
E/IABUtil/Security﹕ Signature verification failed.
E/iabv3﹕ Public key signature doesn't match!
```
All the answers on Google say that we have to change the Security.java, is there any fix?

**Comment by serggl** [comment]
this was a bug in previous version of library. The workaround is to use
license key for the app from the publisher console. But I guess this was
fixed recently...

**Comment by castrojr913** [comment]
@ZiegenGIT That error message doesn't appear with the version `com.anjlab.android.iab.v3:library:1.0.24@aar`
