### ISSUE TITLE
onBillingInitialized() never called

### ISSUE THREAD

**Issue by laurencedawson** [anjlab/android-inapp-billing-v3#64]
After checking if Google Play Services is available and creating an instance of BillingProcessor some users are reporting that the UI never loads. 

The only way this could happen is if "onBillingInitialized" is never called. Is this possible?

Thanks

**Comment by serggl** [comment]
Are you using ProGuard?

**Comment by laurencedawson** [comment]
Yes, but I've added the Google play services rules and the rules mentioned
in the other issues on here.

This is only failing for a very small number of users too.

Thanks

**Comment by laurencedawson** [comment]
Oops didn't mean to close that sorry.

**Comment by serggl** [comment]
@laurencedawson Im afraid you are the only person who can dig into this issue. There is no place for an 'theoretical' fix here. I'll be happy to accept a PR

**Comment by castrojr913** [comment]
This issue appears me when I'm testing with the emulator, i don't see if it's because of Google Play services is installed on the phone.
