### ISSUE TITLE
Got onBillingError: 6

### ISSUE THREAD

**Issue by bagusflyer** [anjlab/android-inapp-billing-v3#72]
I'm using your demo application. What I did:

1. Change the package name to my existing one
2. Change the product id to one existing one

When I click Details button, I got the follow error message:

> Failed to retrieve info for com.myapp.iabtesting:com.myapp.iabtesting.product1: error 6

I'm sure the package name and my product id are correct because I use them in my own application IAB without problem.

Can you help to tell what could be wrong? Thanks

**Comment by serggl** [comment]
Error 6 means "Fatal error during the API action". No Idea what it might caused by. Have you uploaded you app for Alpha/Beta testting in Google Play?

**Comment by bagusflyer** [comment]
Thanks for your reply. I redo everything again. Then it's ok now. Thanks
