### ISSUE TITLE
The isPurchased return true even after the order is cancelled

### ISSUE THREAD

**Issue by bagusflyer** [anjlab/android-inapp-billing-v3#73]
I did some tests on demo application. It works. But I'm confused at one scenario: 

> The isPurchased return true even after the the order is cancelled. 

What I did:

1. Place an order
2. Goto Google wallet to cancel the order
3. Run the application, I found the isPurchased still return true.

What could be wrong? Thanks

**Comment by serggl** [comment]
deja vu?
https://github.com/anjlab/android-inapp-billing-v3/issues/21
