### ISSUE TITLE
Force loadOwnedPurchasesFromGoogle() to fetch data from the IAB server

### ISSUE THREAD

**Issue by sumit-anantwar** [anjlab/android-inapp-billing-v3#77]
Hello,
First of all thanks a lot for this wonderful library.
I am trying to implement it in my app. Everything works fine, except the below situation.

1. Install the app on 2 devices.
2. Purchase the product from one device.
3. Now on the second device 
 - calling .isPurchased() returns false
 - calling .purchase(), makes a request and Google responds "You already own the product".

Now, I guess that .isPurchased() will check only the device's local cache.
So, is there a way to force it to fetch the data from IAB server ?
 ~ OR ~
IAB Server is already responding that the product is owned, so is there any listener which handles this case ?

Thanks a lot.

**Comment by serggl** [comment]
I guess the title for this issue is actually the answer for you. `loadOwnedPurchasesFromGoogle()` should do the trick (it clears local cache and makes request to Google)

**Comment by sumit-anantwar** [comment]
Sorry, I forgot to mention that I am calling .isPurchased() after calling .loadOwnedPurchasesFromGoogle()

Below is the part of the code. Here on the 3rd line .isPurchased() returns false. Am I doing something wrong ?

public void restore(View view){
	if (bp.loadOwnedPurchasesFromGoogle()){
		if (bp.isPurchased(PID)){
			Log.d(LOG_TAG, "Restored");
			finishSuccess();
		}else	{
			showAlert("Purchase was not found on your Account\nPlease use the 'Buy Now' button to unlock the Full Version", false);
		}
	}else{
		Log.d(LOG_TAG, "Have not Purchased");
	}
}

**Comment by serggl** [comment]
maybe google play caching work this way? (updates local cache when new
purchase is initiated). I dont see any problems with your code actually...

**Comment by sumit-anantwar** [comment]
That's what I was afraid of !!
Atleast this time, I wanted my code to be wrong !
Anyways... if this is how it is supposed to be, this no other option...
Thanks a lot for your support, and thanks again for this wonderful library.

**Comment by AhmedAWM** [comment]
I'm having the same issue, loadOwnedPurchasesFromGoogle() always returns false on my other device! Struggling now for over a month.

My code seems to be fine:

```
BillingProcessor  billingProcessor = new BillingProcessor(this,myKEY,this);

Toast.makeText(getApplicationContext(), "Restored Purchase: " + billingProcessor.loadOwnedPurchasesFromGoogle(), Toast.LENGTH_LONG).show();

if(billingProcessor.isPurchased(mySKU)) {
    //Do the thing
} else {
    //Do not do the thing
}
```

Toast message is always "Restored Purchase: false"

**Comment by denieler** [comment]
have the same issue, don't know what to do :(
