### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by retokiefer** [anjlab/android-inapp-billing-v3#79]
Hi,

as soon as I include your library via Gradle I got this error:

Error:Gradle: Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

I know this error may not be related directly to your lib but if you can give assistance to solve the issue I would be glad. Because it occurs when included in the project.

Thanks in advance

Reto

**Comment by retokiefer** [comment]
Sorry: As expected it was independent from your library. You can close the issue.

Thanks for your great work!

**Comment by xbroak** [comment]
I've got this issue also, only happens when include this lib

**Comment by octohub** [comment]
@retokiefer I am dealing with this issue now too. Could you please let me know how you solved this?
@xbroak did you find a solution?
