### ISSUE TITLE
onActivityResult() in Fragments

### ISSUE THREAD

**Issue by tonyp** [anjlab/android-inapp-billing-v3#80]
Okay, I followed the instructions to include the library in my app and it seems to work.
But I ran into an issue as I don't implement all the Billing code in an Activity but in a SettingsFragment.
The problem here is that you depend on a overriding the Activity's onActivityResult method with:

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (!bp.handleActivityResult(requestCode, resultCode, data))
            super.onActivityResult(requestCode, resultCode, data);
    }

When I add this code to my Fragment it will never be called.
It took me a while to find a workaround but I believe expressly calling the Fragment from the Activity could be a solution. I implemented this in my Activity:

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        SettingsFragment fragment = (SettingsFragment) getFragmentManager().findFragmentById(android.R.id.content);
        fragment.onActivityResult(requestCode, resultCode, data);
        }

Is this the correct approach? Is there a better solution?

**Comment by tonyp** [comment]
Although on a second note, this doesn't seem to fully work yet. While my debug view clearly shows that the onActivityResult() in my Fragment and thus bp.handleActivityResult(requestCode, resultCode, data) gets called I still have the issue that the purchase only works on the _second_ press on the purchase buttons.

Pretty much the same issue as described here at SO:
http://stackoverflow.com/questions/28340020/why-android-inapp-billing-v3-library-needs-two-attempts-to-purchase

**Comment by tonyp** [comment]
On another note: 
This SO thread has some more information (and solutions) for the hurdles when using Fragments with Google Billing:
http://stackoverflow.com/questions/14131171/calling-startintentsenderforresult-from-fragment-android-billing-v3

So this isn't a problem by this library per se, but maybe it would be possible to offer a better workaround natively.
The solution I posted in my issue does fully work though, so you can close this issue if you want.
Especially as a similiar one has been posted now: https://github.com/anjlab/android-inapp-billing-v3/issues/81

**Comment by serggl** [comment]
@tonyp you solution looks good to me...I'm afraid this is how Fragments are implemented

**Comment by Rexota** [comment]
@serggl  @tonyp  Where is the solution? Thanks.

**Comment by Waheed388** [comment]
If you are using this Inapp purchase code in fragment class then don't forget to make BillingProcessor as a static object. If you don't make it static then on callback from parent's activity to fragment the BillingProcessor object will be null again.

**Comment by autonomousapps** [comment]
It is absolutely not necessary to have the billing processor be static. There are many options. Among them, injection with, say, Dagger, with a scope that outlives activity destruction. I personally have used a retained fragment and the MVP pattern, and it works fine in production with 300k users per day and significant subscription revenue.
