### ISSUE TITLE
Gradle Error

### ISSUE THREAD

**Issue by homedevs** [anjlab/android-inapp-billing-v3#85]
Hi,

I can't use this library in gradle as I already have   compile 'com.google.android.gms:play-services:7.0.0'  into gradle. I think this is a library conflict so I've removed google play service library from my gradle but it seems like still doesn't have ADMob etc. This is possible if old google play service librarys is being used.

Please let me know the solution.

I'm using ADMOb , In-app billing and Analytic in single project.

**Comment by auchri** [comment]
Did you add the aidl file?
If you added it, remove it and it works.
