### ISSUE TITLE
Public key signature doesn't match!

### ISSUE THREAD

**Issue by xbroak** [anjlab/android-inapp-billing-v3#88]
05-09 17:32:06.870  12246-12246/verification failed.
05-09 17:32:06.870  12246-12246/E/iabv3﹕ Public key signature doesn't match!
05-09 17:32:06.870  12246-12246/E/KFF﹕ An unknown error occurred in billing: 102

I've uploaded the APK to alpha, running the signed build and the purchase is made and successfully paid for, when the dialogue for successful payment closes, it triggers the error 102, what gives?

**Comment by ReginFell** [comment]
Have same problem

**Comment by timoschwarzer** [comment]
Did you sign the APK you are using on your phone (probably a debug artifact)?
For Android Studio Users: https://www.jetbrains.com/idea/help/generating-an-apk-in-the-debug-mode.html

**Comment by xbroak** [comment]
Yep! Signed, uploaded to alpha channel and installed on phone

------ Original Message ------

**Comment by xbroak** [comment]
Any news on this?

**Comment by mustii82** [comment]
We know about this problem Fix and Discussion here :) #101

**Comment by serggl** [comment]
duplicates #100. closing this
