### ISSUE TITLE
ANR caused by  eventHandler.onBillingError 

### ISSUE THREAD

**Issue by druidamix** [anjlab/android-inapp-billing-v3#90]
Hi,
When eventHandler.onBillingError(Constants.BILLING_ERROR_INVALID_SIGNATURE, null); is executed, it causes an exception and then an anr.

BillinProcessor.java line 323:

	if (purchasePayload.equals(developerPayload)) {
					if (verifyPurchaseSignature(productId, purchaseData, dataSignature)) {
						BillingCache cache = purchasedSubscription ? cachedSubscriptions : cachedProducts;
						cache.put(productId, purchaseData, dataSignature);
						if (eventHandler != null)
							eventHandler.onProductPurchased(productId, new TransactionDetails(new PurchaseInfo(purchaseData, dataSignature)));
					} else {
						Log.e(LOG_TAG, "Public key signature doesn't match!");
						if (eventHandler != null)
							eventHandler.onBillingError(Constants.BILLING_ERROR_INVALID_SIGNATURE, null);
//The previous call throws this null pointer exception :Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference

**Comment by serggl** [comment]
so, seems like your implementation of `onBillingError` callback causes ANR, isnt it?
